using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Vixen.Module.CommandSpec;

namespace Vixen.Sys {
	// This is what represents an editable command generated by a user.
	// This has no knowledge of the command behavior, ICommandSpec does.  This is a
	// command spec with parameter values to give it meaning.
	public class Command {
		public Command(Guid commandSpecId, params object[] parameterValues) {
			Spec = Server.ModuleManagement.GetCommandSpec(commandSpecId);
			ParameterValues = parameterValues;
		}

		public object[] ParameterValues { get; private set; }
		public ICommandSpecModuleInstance Spec { get; private set; }
	}
}
