// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vixen.Script.VB
{
    using Vixen.Sys;
    using Vixen.Module.Effect;
    using System.Collections.Generic;
    using System.Linq;
    using System;
    
    
    #line 1 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ScriptFramework : ScriptFrameworkBase
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write(@"Option Strict Off

imports System
imports System.Collections.Generic
imports System.Linq
imports System.Text
imports System.Threading
imports System.Dynamic
imports Vixen.Sys
imports Vixen.Common
imports Vixen.Module.Sequence
imports Vixen.Script
imports CommandStandard

Namespace ");
            
            #line 22 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(" \r\n\tPartial Public Class ");
            
            #line 23 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"
		Inherits UserScriptHost
		'Private _nodes() As UserScriptNode
		Private _nodes
		' Effect name : effect type id
		Private _effects As Dictionary(Of String, Guid)

		Public Sub New
			_nodes = Vixen.Sys.Execution.Nodes.Select(Function(x) New UserScriptNode(x)).ToArray()
			' Need to copy the command dictionary made in code, but in such a way that
			' it can be built when this is executing..
			_effects = New Dictionary(Of String, Guid)
");
            
            #line 35 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"

	foreach(string effectName in _effects.Keys) {

            
            #line default
            #line hidden
            this.Write("\t\t\t_effects.Add(\"");
            
            #line 38 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectName));
            
            #line default
            #line hidden
            this.Write("\", New Guid(\"");
            
            #line 38 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_effects[effectName].TypeId));
            
            #line default
            #line hidden
            this.Write("\"))\r\n");
            
            #line 39 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\tEnd Sub\r\n\r\n\t\tPublic Overrides Property Sequence() As ScriptSequence \r\n\t\t\tGe" +
                    "t\r\n\t\t\t\tReturn MyBase.Sequence\r\n\t\t\tEnd Get\r\n\t\t\tSet\r\n\t\t\t\tMyBase.Sequence = Value\r\n" +
                    "\t\t\t\t\'_fixtures = _\r\n\t\t\t\t\'\tvalue.Fixtures.Select(Function(x) New UserScriptFixtur" +
                    "e(x)).ToArray()\r\n\t\t\tEnd Set\r\n\t\tEnd Property\r\n\r\n\t\t\' Arg 0: IEnumerable<UserScript" +
                    "Channel>\r\n\t\t\' Arg 1: int startTime\r\n\t\t\' Arg 2: int timeSpan\r\n\t\t\' Arg 3: Start of" +
                    " command-specific parameters\r\n\t\t\'Protected Sub _InvokeEffect(effectName As Strin" +
                    "g, ParamArray args() as object)\r\n\t\tProtected Sub _InvokeEffect(effectName as Str" +
                    "ing, channels as IEnumerable(Of UserScriptNode), startTime as Long, timeSpan as " +
                    "Long, effectName as String, ParamArray args() as object)\r\n\t\t\t\'Dim effectId as Gu" +
                    "id\r\n\t\t\t\'Dim channels as IEnumerable(Of UserScriptChannel)\r\n\t\t\t\'Dim startTime as " +
                    "Integer\r\n\t\t\t\'Dim timeSpan as Integer\r\n\t\t\tIf _effects.TryGetValue(effectName, eff" +
                    "ectId) Then\r\n\t\t\t\'\tIf args.Length < 3 Then\r\n\t\t\t\'\t\tThrow New ArgumentException(\"In" +
                    "valid parameter count to invoke an effect.\")\r\n\t\t\t\'\tEnd If\r\n\t\t\t\'\t\' Argument 1: IE" +
                    "numerable<UserScriptChannel>\r\n\t\t\t\'\tchannels = args(0)\r\n\t\t\t\'\tIf channels is Nothi" +
                    "ng Then\r\n\t\t\t\'\t\tThrow New ArgumentException(\"First parameter must be a channel co" +
                    "llection.\")\r\n\t\t\t\'\tEnd If\r\n\t\t\t\'\t\' Argument 2: int (start time)\r\n\t\t\t\'\tstartTime = " +
                    "args(1)\r\n\t\t\t\'\t\' Argument 3: int (time span)\r\n\t\t\t\'\ttimeSpan = args(2)\r\n\t\t\t\t\r\n\t\t\t\'" +
                    "\tSequence.InsertData(channels.Select(Function(x) x.Channel).ToArray() , startTim" +
                    "e, timeSpan, New Command(effectId, args.Skip(3).ToArray()))\r\n\t\t\t\tSequence.Insert" +
                    "Data(channels.Select(Function(x) x.Node).ToArray() , startTime, timeSpan, New Co" +
                    "mmand(effectId, args.ToArray()))\r\n\t\t\tEnd If\r\n\t\tEnd Sub\r\n\r\n");
            
            #line 82 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"

	foreach(string effectName in _effects.Keys) {
		IEffectModuleInstance effect = _effects[effectName];
		string effectParameters =
			string.Join(", ",
			(from parameter in effect.Parameters
			select parameter.Name + " As " + parameter.Type).ToArray());
		string parameterNames =
			string.Join(", ",
			(from parameter in effect.Parameters
			select parameter.Name).ToArray());

            
            #line default
            #line hidden
            this.Write("\t\t\' Original name: ");
            
            #line 94 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effect.EffectName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tPublic Sub ");
            
            #line 95 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectName));
            
            #line default
            #line hidden
            this.Write("(targetNodes As IEnumerable(Of UserScriptNode), startTime As Long, timeSpan As Lo" +
                    "ng, ");
            
            #line 95 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t_InvokeEffect(\"");
            
            #line 96 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectName));
            
            #line default
            #line hidden
            this.Write("\", targetNodes, startTime, timeSpan, ");
            
            #line 96 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterNames));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\tEnd Sub\r\n\r\n\t\tPublic Sub ");
            
            #line 99 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectName));
            
            #line default
            #line hidden
            this.Write("(targetNodes As IEnumerable(Of UserScriptNode), timeSpan As Long, ");
            
            #line 99 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t_InvokeEffect(\"");
            
            #line 100 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(effectName));
            
            #line default
            #line hidden
            this.Write("\", targetNodes, 0, timeSpan, ");
            
            #line 100 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterNames));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\tEnd Sub\r\n\r\n");
            
            #line 103 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
 } 
            
            #line default
            #line hidden
            
            #line 104 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"

	// This needs to match the node collection that the script created in its constructor.
	ChannelNode[] nodes = Vixen.Sys.Execution.Nodes.ToArray();
	List<string> usedNames = new List<string>();
	for(int i=0; i < nodes.Length; i++) { 
            
            #line default
            #line hidden
            this.Write("\t\t\' Original name: ");
            
            #line 109 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nodes[i].Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tPublic ReadOnly Property ");
            
            #line 110 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScriptHostGenerator.Fix(nodes[i].Name, usedNames)));
            
            #line default
            #line hidden
            this.Write("() As Object\r\n\t\t\tGet\r\n\t\t\t\tReturn _nodes(");
            
            #line 112 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\tEnd Get\r\n\t\tEnd Property\r\n");
            
            #line 115 "C:\Users\Development\Documents\Visual Studio 2010\Projects\Vixen\2011\Vixen.System\Script\VB\ScriptFramework.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\tEnd Class\r\nEnd Namespace\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class ScriptFrameworkBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
