//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VixenModules.EffectEditor.EffectDescriptorAttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EffectDescriptionDescriptors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectDescriptionDescriptors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VixenModules.EffectEditor.EffectDescriptorAttributes.EffectDescriptionDescriptors" +
                            "", typeof(EffectDescriptionDescriptors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether each individual element is alternated independantly or controlled by the depth of the effect..
        /// </summary>
        internal static string AlternatingDepth {
            get {
                return ResourceManager.GetString("AlternatingDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of background chunks..
        /// </summary>
        internal static string BackgroundChunks {
            get {
                return ResourceManager.GetString("BackgroundChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Background color..
        /// </summary>
        internal static string BackGroundColor {
            get {
                return ResourceManager.GetString("BackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of background skips..
        /// </summary>
        internal static string BackgroundSkips {
            get {
                return ResourceManager.GetString("BackgroundSkips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of Balls displayed..
        /// </summary>
        internal static string BallCount {
            get {
                return ResourceManager.GetString("BallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the individual empty balls..
        /// </summary>
        internal static string BallEdgeWidth {
            get {
                return ResourceManager.GetString("BallEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the type of fill for the balls..
        /// </summary>
        internal static string BallFill {
            get {
                return ResourceManager.GetString("BallFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the Ball..
        /// </summary>
        internal static string BallSize {
            get {
                return ResourceManager.GetString("BallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects between Bounce and Wrap..
        /// </summary>
        internal static string BallType {
            get {
                return ResourceManager.GetString("BallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the brightness of the base color of the effect..
        /// </summary>
        internal static string BaseBrightness {
            get {
                return ResourceManager.GetString("BaseBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the base color that will be used for the background of the effect..
        /// </summary>
        internal static string BaseColor {
            get {
                return ResourceManager.GetString("BaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the look of the blade..
        /// </summary>
        internal static string BladeType {
            get {
                return ResourceManager.GetString("BladeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies the gradient blend vertically..
        /// </summary>
        internal static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Simple or Advanced border width control..
        /// </summary>
        internal static string BorderMode {
            get {
                return ResourceManager.GetString("BorderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the overall size of the border..
        /// </summary>
        internal static string BorderSize {
            get {
                return ResourceManager.GetString("BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Single or Independent Border width control..
        /// </summary>
        internal static string BorderType {
            get {
                return ResourceManager.GetString("BorderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Border width..
        /// </summary>
        internal static string BorderWidth {
            get {
                return ResourceManager.GetString("BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Bottom Border Width..
        /// </summary>
        internal static string BottomBorderWidth {
            get {
                return ResourceManager.GetString("BottomBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the brightness of the effect..
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the type of pattern..
        /// </summary>
        internal static string ButterflyType {
            get {
                return ResourceManager.GetString("ButterflyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the size of the hub or hole in the center of the Pinwheel..
        /// </summary>
        internal static string CenterHub {
            get {
                return ResourceManager.GetString("CenterHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the text into view and stops it in the center..
        /// </summary>
        internal static string CenterStop {
            get {
                return ResourceManager.GetString("CenterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center each line of text instead of left justified..
        /// </summary>
        internal static string CenterText {
            get {
                return ResourceManager.GetString("CenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the horizontal plane..
        /// </summary>
        internal static string CenterX {
            get {
                return ResourceManager.GetString("CenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the vertical plane..
        /// </summary>
        internal static string CenterY {
            get {
                return ResourceManager.GetString("CenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ball color when balls collide..
        /// </summary>
        internal static string ChangeCollideColor {
            get {
                return ResourceManager.GetString("ChangeCollideColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets percentage of change..
        /// </summary>
        internal static string ChangePercent {
            get {
                return ResourceManager.GetString("ChangePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the ball direction when balls collide..
        /// </summary>
        internal static string Collide {
            get {
                return ResourceManager.GetString("Collide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the number of Circles or radial patterns in the effect..
        /// </summary>
        internal static string CircleCount {
            get {
                return ResourceManager.GetString("CircleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the individual circles, may need to increase when using Loaction..
        /// </summary>
        internal static string CircleEdgeWidth {
            get {
                return ResourceManager.GetString("CircleEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the way the circle is filled..
        /// </summary>
        internal static string CircleFill {
            get {
                return ResourceManager.GetString("CircleFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color of the effect..
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the color is handled..
        /// </summary>
        internal static string ColorHandling {
            get {
                return ResourceManager.GetString("ColorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color scheme..
        /// </summary>
        internal static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the Type of Color..
        /// </summary>
        internal static string ColorType {
            get {
                return ResourceManager.GetString("ColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how many levels deep the effect should be grouped..
        /// </summary>
        internal static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets percent of deviation..
        /// </summary>
        internal static string DeviationPercent {
            get {
                return ResourceManager.GetString("DeviationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the direction of the effect..
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the type of movement..
        /// </summary>
        internal static string EffectType {
            get {
                return ResourceManager.GetString("EffectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables a default brightness for the background in the effect. The background will be based on the foreground color selections..
        /// </summary>
        internal static string EnableMinimumBrightness {
            get {
                return ResourceManager.GetString("EnableMinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many explosions occur..
        /// </summary>
        internal static string Explosions {
            get {
                return ResourceManager.GetString("Explosions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends the pulse to the end of the effect from beyond it&apos;s normal ending position. The extension will be at the ending color and ending value of the brightness intensity. If the intensity ends in zero, this will have no effect..
        /// </summary>
        internal static string ExtendPulseEnd {
            get {
                return ResourceManager.GetString("ExtendPulseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends the pulse back to the start of the effect from it&apos;s normal starting position. The extension will be at the starting color and starting brightness intensity. If the intensity starts at zero, which is the default, this will have no effect..
        /// </summary>
        internal static string ExtendPulseStart {
            get {
                return ResourceManager.GetString("ExtendPulseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file name..
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times the effect so that it will fit in the allotted time span..
        /// </summary>
        internal static string FitTime {
            get {
                return ResourceManager.GetString("FitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of flakes..
        /// </summary>
        internal static string FlakeCount {
            get {
                return ResourceManager.GetString("FlakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the type of snowflake..
        /// </summary>
        internal static string FlakeType {
            get {
                return ResourceManager.GetString("FlakeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets flicker frequency in changes per second..
        /// </summary>
        internal static string FlickerFrequency {
            get {
                return ResourceManager.GetString("FlickerFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets percentage of flicker..
        /// </summary>
        internal static string FlickerPercent {
            get {
                return ResourceManager.GetString("FlickerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text font..
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the frames per second rate..
        /// </summary>
        internal static string FramesPerSecond {
            get {
                return ResourceManager.GetString("FramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the garland type..
        /// </summary>
        internal static string GarlandType {
            get {
                return ResourceManager.GetString("GarlandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the speed at which a gif animates if the image is a animated gif..
        /// </summary>
        internal static string GifSpeed {
            get {
                return ResourceManager.GetString("GifSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color gradient and brightness curve that are associated together to provide the color(s) for the effect..
        /// </summary>
        internal static string GradientLevelPair {
            get {
                return ResourceManager.GetString("GradientLevelPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the gradient is applied to the effect..
        /// </summary>
        internal static string GradientMode {
            get {
                return ResourceManager.GetString("GradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the stop point for the color in the gradient..
        /// </summary>
        internal static string GradientPosition {
            get {
                return ResourceManager.GetString("GradientPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the grouping together of elements that will be in the same state..
        /// </summary>
        internal static string GroupLevel {
            get {
                return ResourceManager.GetString("GroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow the legs of the spiral..
        /// </summary>
        internal static string Grow {
            get {
                return ResourceManager.GetString("Grow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the height of the fire..
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether there are highlights added..
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the horizontal plane..
        /// </summary>
        internal static string HorizontalOffset {
            get {
                return ResourceManager.GetString("HorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color of the fire..
        /// </summary>
        internal static string HueShift {
            get {
                return ResourceManager.GetString("HueShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include 45 Point Flakes..
        /// </summary>
        internal static string Include45Pt {
            get {
                return ResourceManager.GetString("Include45Pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies how often the effect should switch in milliseconds..
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the offset into the color list for the alternate state in the effect. One is the default and would shift the colors back and forth by one..
        /// </summary>
        internal static string IntervalSkip {
            get {
                return ResourceManager.GetString("IntervalSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of times the pattern repeats over the timespan..
        /// </summary>
        internal static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Left Border Width..
        /// </summary>
        internal static string LeftBorderWidth {
            get {
                return ResourceManager.GetString("LeftBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the location..
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max angle the Snowflake moves..
        /// </summary>
        internal static string MaxAngle {
            get {
                return ResourceManager.GetString("MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the maximum brightness of a pulse..
        /// </summary>
        internal static string MaxBrightness {
            get {
                return ResourceManager.GetString("MaxBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Direction in Degrees..
        /// </summary>
        internal static string MaxDirection {
            get {
                return ResourceManager.GetString("MaxDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max angle the Meteor moves..
        /// </summary>
        internal static string MaxMeteorAngle {
            get {
                return ResourceManager.GetString("MaxMeteorAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors are not used when Rainbow is selected..
        /// </summary>
        internal static string MeteorType {
            get {
                return ResourceManager.GetString("MeteorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min angle the Snowflake moves..
        /// </summary>
        internal static string MinAngle {
            get {
                return ResourceManager.GetString("MinAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the minimum brightness of a pulse..
        /// </summary>
        internal static string MinBrightness {
            get {
                return ResourceManager.GetString("MinBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Direction in Degrees..
        /// </summary>
        internal static string MinDirection {
            get {
                return ResourceManager.GetString("MinDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the default brightness of the background in the effect. Sometimes a zero value may be necesary to get certain behaviors in layer mixing..
        /// </summary>
        internal static string MinimumBrightness {
            get {
                return ResourceManager.GetString("MinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min angle the Meteor moves..
        /// </summary>
        internal static string MinMeteorAngle {
            get {
                return ResourceManager.GetString("MinMeteorAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control type of movement, either Speed and Iterations..
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the Type of Movement..
        /// </summary>
        internal static string MovementType {
            get {
                return ResourceManager.GetString("MovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the direction of the strings and controls how the effect is oriented on the element..
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Outer border start location..
        /// </summary>
        internal static string OuterBorderStarts {
            get {
                return ResourceManager.GetString("OuterBorderStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how fast the particles fade..
        /// </summary>
        internal static string ParticleFade {
            get {
                return ResourceManager.GetString("ParticleFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many particles will be created..
        /// </summary>
        internal static string Particles {
            get {
                return ResourceManager.GetString("Particles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of pixels on each string..
        /// </summary>
        internal static string PixelsPerString {
            get {
                return ResourceManager.GetString("PixelsPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the centering of the text on the element..
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long each pulse is in milliseconds..
        /// </summary>
        internal static string PulseDuration {
            get {
                return ResourceManager.GetString("PulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many milliseconds the individual pulses overlap..
        /// </summary>
        internal static string PulseOverlap {
            get {
                return ResourceManager.GetString("PulseOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the individual pulse shape..
        /// </summary>
        internal static string PulseShape {
            get {
                return ResourceManager.GetString("PulseShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long each pulse is as a percentage of the spin..
        /// </summary>
        internal static string PulseSpinPercent {
            get {
                return ResourceManager.GetString("PulseSpinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how individual pulses are applied across the effect..
        /// </summary>
        internal static string PulseType {
            get {
                return ResourceManager.GetString("PulseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the direction of the effect to In or out..
        /// </summary>
        internal static string RadialDirection {
            get {
                return ResourceManager.GetString("RadialDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of the radial pattern..
        /// </summary>
        internal static string RadialSpeed {
            get {
                return ResourceManager.GetString("RadialSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The radius of the circle over the time of the effect..
        /// </summary>
        internal static string RadiusCurve {
            get {
                return ResourceManager.GetString("RadiusCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Intensity for each element of the effect..
        /// </summary>
        internal static string RandomIntensity {
            get {
                return ResourceManager.GetString("RandomIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new Meteors at a Random Position.
        /// </summary>
        internal static string RandomPosition {
            get {
                return ResourceManager.GetString("RandomPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates random size balls up to the Radius value...
        /// </summary>
        internal static string RandomRadius {
            get {
                return ResourceManager.GetString("RandomRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Random Speed settings..
        /// </summary>
        internal static string RandomSpeed {
            get {
                return ResourceManager.GetString("RandomSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of times the color pattern repeats within the pattern..
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes direction of effect..
        /// </summary>
        internal static string ReverseDirection {
            get {
                return ResourceManager.GetString("ReverseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many revolutions of the spin will occur..
        /// </summary>
        internal static string RevolutionCount {
            get {
                return ResourceManager.GetString("RevolutionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the frequency in Hz at which the spin occurs..
        /// </summary>
        internal static string RevolutionFrequency {
            get {
                return ResourceManager.GetString("RevolutionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the duration in milliseconds at which the spin occurs..
        /// </summary>
        internal static string RevolutionTime {
            get {
                return ResourceManager.GetString("RevolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Right Border Width..
        /// </summary>
        internal static string RightBorderWidth {
            get {
                return ResourceManager.GetString("RightBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of twist in the spiral..
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a pixel to the inner corners of the border..
        /// </summary>
        internal static string RoundEdges {
            get {
                return ResourceManager.GetString("RoundEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the percent of the scaling to reduce the size of large images to fit..
        /// </summary>
        internal static string ScalePercent {
            get {
                return ResourceManager.GetString("ScalePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically sets the scaling to match the grid size..
        /// </summary>
        internal static string ScaleToGrid {
            get {
                return ResourceManager.GetString("ScaleToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a 3D effect..
        /// </summary>
        internal static string Show3D {
            get {
                return ResourceManager.GetString("Show3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink the legs of the spiral..
        /// </summary>
        internal static string Shrink {
            get {
                return ResourceManager.GetString("Shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the radial effect..
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the space between garlands..
        /// </summary>
        internal static string Spacing {
            get {
                return ResourceManager.GetString("Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the Speed around the Speed level by the amount of variation...
        /// </summary>
        internal static string SpeedVariation {
            get {
                return ResourceManager.GetString("SpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the individual spins occur..
        /// </summary>
        internal static string SpinSpeedFormat {
            get {
                return ResourceManager.GetString("SpinSpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the color is a static color..
        /// </summary>
        internal static string StaticColorIndicator {
            get {
                return ResourceManager.GetString("StaticColorIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that the effect should be the same on all elements..
        /// </summary>
        internal static string StaticEffect {
            get {
                return ResourceManager.GetString("StaticEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of strings the effect will use..
        /// </summary>
        internal static string StringCount {
            get {
                return ResourceManager.GetString("StringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of TailLength..
        /// </summary>
        internal static string TailLength {
            get {
                return ResourceManager.GetString("TailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the target elements are treated. Either as individual strings or by their actual location..
        /// </summary>
        internal static string TargetPositioning {
            get {
                return ResourceManager.GetString("TargetPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the brightness of the text in the effect..
        /// </summary>
        internal static string TextBrightness {
            get {
                return ResourceManager.GetString("TextBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to be displayed..
        /// </summary>
        internal static string TextLines {
            get {
                return ResourceManager.GetString("TextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the orientation of the text lines..
        /// </summary>
        internal static string TextMode {
            get {
                return ResourceManager.GetString("TextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how thick the spiral leg is..
        /// </summary>
        internal static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Top Border Width..
        /// </summary>
        internal static string TopBorderWidth {
            get {
                return ResourceManager.GetString("TopBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long the averge pulse time is in the twinkle..
        /// </summary>
        internal static string TwinkleAvgPulseTime {
            get {
                return ResourceManager.GetString("TwinkleAvgPulseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much of the effect by percent is covered in twinkles..
        /// </summary>
        internal static string TwinkleCoverage {
            get {
                return ResourceManager.GetString("TwinkleCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether each individual element is twinkled independantly or controled by the depth of the effect..
        /// </summary>
        internal static string TwinkleDepth {
            get {
                return ResourceManager.GetString("TwinkleDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much percent variation in the brightness level of each pulse in the twinkle..
        /// </summary>
        internal static string TwinkleLevelVariation {
            get {
                return ResourceManager.GetString("TwinkleLevelVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much percent variation in the time of each pulse in the twinkle..
        /// </summary>
        internal static string TwinklePulseTimeVariation {
            get {
                return ResourceManager.GetString("TwinklePulseTimeVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the amount of rotation or twist the Pinwheel arm has..
        /// </summary>
        internal static string Twist {
            get {
                return ResourceManager.GetString("Twist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if a underlying base color should be used..
        /// </summary>
        internal static string UseBaseColor {
            get {
                return ResourceManager.GetString("UseBaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the velocity of the particles..
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the orientation of the gradient..
        /// </summary>
        internal static string VerticalBlend {
            get {
                return ResourceManager.GetString("VerticalBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the vertical plane..
        /// </summary>
        internal static string VerticalOffset {
            get {
                return ResourceManager.GetString("VerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the wave accelerates out from the center over time. .
        /// </summary>
        internal static string WaveAcceleration {
            get {
                return ResourceManager.GetString("WaveAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width over time of the effect..
        /// </summary>
        internal static string WidthCurve {
            get {
                return ResourceManager.GetString("WidthCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of passes the wipe makes..
        /// </summary>
        internal static string WipeCount {
            get {
                return ResourceManager.GetString("WipeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the length of the pulse as a percentage of the effect time..
        /// </summary>
        internal static string WipePulsePercent {
            get {
                return ResourceManager.GetString("WipePulsePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the wipe behaves. Either by a count of passes, or by time related to pulse length..
        /// </summary>
        internal static string WipeType {
            get {
                return ResourceManager.GetString("WipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can help to adjust the position of the effect. May not work in all cases..
        /// </summary>
        internal static string XOffset {
            get {
                return ResourceManager.GetString("XOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can help to adjust the position of the effect. May not work in all cases..
        /// </summary>
        internal static string YOffset {
            get {
                return ResourceManager.GetString("YOffset", resourceCulture);
            }
        }
    }
}
