//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VixenModules.EffectEditor.EffectDescriptorAttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EffectDescriptionDescriptors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectDescriptionDescriptors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VixenModules.EffectEditor.EffectDescriptorAttributes.EffectDescriptionDescriptors" +
                            "", typeof(EffectDescriptionDescriptors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When selected, the effect does not fill gaps in the marks with a REST..
        /// </summary>
        internal static string AllowMarkGaps {
            get {
                return ResourceManager.GetString("AllowMarkGaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether each individual element is alternated independantly or controlled by the depth of the effect..
        /// </summary>
        internal static string AlternatingDepth {
            get {
                return ResourceManager.GetString("AlternatingDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the rotation angle..
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the angle speed of the shape..
        /// </summary>
        internal static string AngleSpeed {
            get {
                return ResourceManager.GetString("AngleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the angle speed around the angle speed level by the amount of variation..
        /// </summary>
        internal static string AngleSpeedVariation {
            get {
                return ResourceManager.GetString("AngleSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the time the word is displayed to auto fit between words either side..
        /// </summary>
        internal static string AutoFit {
            get {
                return ResourceManager.GetString("AutoFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of background chunks..
        /// </summary>
        internal static string BackgroundChunks {
            get {
                return ResourceManager.GetString("BackgroundChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Background color..
        /// </summary>
        internal static string BackGroundColor {
            get {
                return ResourceManager.GetString("BackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of background skips..
        /// </summary>
        internal static string BackgroundSkips {
            get {
                return ResourceManager.GetString("BackgroundSkips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of Balls displayed..
        /// </summary>
        internal static string BallCount {
            get {
                return ResourceManager.GetString("BallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the individual empty balls..
        /// </summary>
        internal static string BallEdgeWidth {
            get {
                return ResourceManager.GetString("BallEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the type of fill for the balls..
        /// </summary>
        internal static string BallFill {
            get {
                return ResourceManager.GetString("BallFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the Ball..
        /// </summary>
        internal static string BallSize {
            get {
                return ResourceManager.GetString("BallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects between Bounce and Wrap..
        /// </summary>
        internal static string BallType {
            get {
                return ResourceManager.GetString("BallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the brightness of the base color of the effect..
        /// </summary>
        internal static string BaseBrightness {
            get {
                return ResourceManager.GetString("BaseBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the base color that will be used for the background of the effect..
        /// </summary>
        internal static string BaseColor {
            get {
                return ResourceManager.GetString("BaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the look of the blade..
        /// </summary>
        internal static string BladeType {
            get {
                return ResourceManager.GetString("BladeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies the gradient blend vertically..
        /// </summary>
        internal static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Border height..
        /// </summary>
        internal static string BorderHeight {
            get {
                return ResourceManager.GetString("BorderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Simple or Advanced border width control..
        /// </summary>
        internal static string BorderMode {
            get {
                return ResourceManager.GetString("BorderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from a list of Border shapes..
        /// </summary>
        internal static string BorderShapes {
            get {
                return ResourceManager.GetString("BorderShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the overall size of the border..
        /// </summary>
        internal static string BorderSize {
            get {
                return ResourceManager.GetString("BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Thickness of the border..
        /// </summary>
        internal static string BorderThickness {
            get {
                return ResourceManager.GetString("BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Single or Independent Border width control..
        /// </summary>
        internal static string BorderType {
            get {
                return ResourceManager.GetString("BorderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Border width..
        /// </summary>
        internal static string BorderWidth {
            get {
                return ResourceManager.GetString("BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissolves or fills the element in both directions one after another..
        /// </summary>
        internal static string BothDirections {
            get {
                return ResourceManager.GetString("BothDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Bottom Border Width..
        /// </summary>
        internal static string BottomBorderWidth {
            get {
                return ResourceManager.GetString("BottomBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the brightness of the effect..
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts how fast the build-up of Snow is..
        /// </summary>
        internal static string BuildUpSpeed {
            get {
                return ResourceManager.GetString("BuildUpSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the type of pattern..
        /// </summary>
        internal static string ButterflyType {
            get {
                return ResourceManager.GetString("ButterflyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the size of the hub or hole in the center of the Pinwheel..
        /// </summary>
        internal static string CenterHub {
            get {
                return ResourceManager.GetString("CenterHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the Shape size around the Size level by the amount of variation..
        /// </summary>
        internal static string CenterSize {
            get {
                return ResourceManager.GetString("CenterSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the text into view and stops it in the center..
        /// </summary>
        internal static string CenterStop {
            get {
                return ResourceManager.GetString("CenterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center each line of text instead of left justified..
        /// </summary>
        internal static string CenterText {
            get {
                return ResourceManager.GetString("CenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the horizontal plane..
        /// </summary>
        internal static string CenterX {
            get {
                return ResourceManager.GetString("CenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the vertical plane..
        /// </summary>
        internal static string CenterY {
            get {
                return ResourceManager.GetString("CenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ball color when balls collide..
        /// </summary>
        internal static string ChangeCollideColor {
            get {
                return ResourceManager.GetString("ChangeCollideColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets percentage of change..
        /// </summary>
        internal static string ChangePercent {
            get {
                return ResourceManager.GetString("ChangePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from a list of Christmas shapes..
        /// </summary>
        internal static string ChristmasShapes {
            get {
                return ResourceManager.GetString("ChristmasShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the number of Circles or radial patterns in the effect..
        /// </summary>
        internal static string CircleCount {
            get {
                return ResourceManager.GetString("CircleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the individual circles, may need to increase when using Loaction..
        /// </summary>
        internal static string CircleEdgeWidth {
            get {
                return ResourceManager.GetString("CircleEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the way the circle is filled..
        /// </summary>
        internal static string CircleFill {
            get {
                return ResourceManager.GetString("CircleFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the ball direction when balls collide..
        /// </summary>
        internal static string Collide {
            get {
                return ResourceManager.GetString("Collide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color of the effect..
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fills the shape with the fill color..
        /// </summary>
        internal static string ColorFill {
            get {
                return ResourceManager.GetString("ColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the color is handled..
        /// </summary>
        internal static string ColorHandling {
            get {
                return ResourceManager.GetString("ColorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreads the Color across each count or entire length of the effect..
        /// </summary>
        internal static string ColorPerCount {
            get {
                return ResourceManager.GetString("ColorPerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled the color will change for each Step variation..
        /// </summary>
        internal static string ColorPerStep {
            get {
                return ResourceManager.GetString("ColorPerStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color scheme..
        /// </summary>
        internal static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the Type of Color..
        /// </summary>
        internal static string ColorType {
            get {
                return ResourceManager.GetString("ColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will fade each displayed count down time..
        /// </summary>
        internal static string CountDownFade {
            get {
                return ResourceManager.GetString("CountDownFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vary the size of the Count down value..
        /// </summary>
        internal static string CountDownSizeMode {
            get {
                return ResourceManager.GetString("CountDownSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the starting time in seconds for the count to begin..
        /// </summary>
        internal static string CountDownTime {
            get {
                return ResourceManager.GetString("CountDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the type as count down the time to the end of the effect, or count up/down from user specified start time..
        /// </summary>
        internal static string CountDownType {
            get {
                return ResourceManager.GetString("CountDownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates Meteors for each string..
        /// </summary>
        internal static string CountPerString {
            get {
                return ResourceManager.GetString("CountPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuts the cross Height to Width ratio..
        /// </summary>
        internal static string CrossSizeRatio {
            get {
                return ResourceManager.GetString("CrossSizeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will cycle through gradient colors for each word..
        /// </summary>
        internal static string CycleColor {
            get {
                return ResourceManager.GetString("CycleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of time in milliseconds for one complete on and off cycle..
        /// </summary>
        internal static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alters the cycle time as a percentage of the Cycle Time parameter above. Used to vary the strobe speed over time..
        /// </summary>
        internal static string CycleVariation {
            get {
                return ResourceManager.GetString("CycleVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the density of the elements..
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how many levels deep the effect should be grouped..
        /// </summary>
        internal static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets percent of deviation..
        /// </summary>
        internal static string DeviationPercent {
            get {
                return ResourceManager.GetString("DeviationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the direction of the effect..
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will move the text basd on direction over the duration of each displayed word..
        /// </summary>
        internal static string DirectionPerWord {
            get {
                return ResourceManager.GetString("DirectionPerWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissolves or fills the element in both directions at the same time..
        /// </summary>
        internal static string DirectionsTogether {
            get {
                return ResourceManager.GetString("DirectionsTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flips the direction of the sequential dissolve..
        /// </summary>
        internal static string DissolveFlip {
            get {
                return ResourceManager.GetString("DissolveFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mark Collection to align changes to the Dissolve pattern..
        /// </summary>
        internal static string DissolveMarkCollection {
            get {
                return ResourceManager.GetString("DissolveMarkCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the type of movement..
        /// </summary>
        internal static string EffectType {
            get {
                return ResourceManager.GetString("EffectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a Ground level for the Meteors to hit..
        /// </summary>
        internal static string EnableGroundLevel {
            get {
                return ResourceManager.GetString("EnableGroundLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables a default brightness for the background in the effect. The background will be based on the foreground color selections..
        /// </summary>
        internal static string EnableMinimumBrightness {
            get {
                return ResourceManager.GetString("EnableMinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many explosions occur..
        /// </summary>
        internal static string Explosions {
            get {
                return ResourceManager.GetString("Explosions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends the pulse to the end of the effect from beyond it&apos;s normal ending position. The extension will be at the ending color and ending value of the brightness intensity. If the intensity ends in zero, this will have no effect..
        /// </summary>
        internal static string ExtendPulseEnd {
            get {
                return ResourceManager.GetString("ExtendPulseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends the pulse back to the start of the effect from it&apos;s normal starting position. The extension will be at the starting color and starting brightness intensity. If the intensity starts at zero, which is the default, this will have no effect..
        /// </summary>
        internal static string ExtendPulseStart {
            get {
                return ResourceManager.GetString("ExtendPulseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the eyes are handled..
        /// </summary>
        internal static string EyeMode {
            get {
                return ResourceManager.GetString("EyeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file name..
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a film spinner around the number..
        /// </summary>
        internal static string FilmSpinner {
            get {
                return ResourceManager.GetString("FilmSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the swipe color of the film spinner..
        /// </summary>
        internal static string FilmSpinnerColors {
            get {
                return ResourceManager.GetString("FilmSpinnerColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the gradient is applied to the swipe color of the film spinner..
        /// </summary>
        internal static string FilmSpinnerGradientMode {
            get {
                return ResourceManager.GetString("FilmSpinnerGradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects what source is used to determine explosions..
        /// </summary>
        internal static string FireworksSource {
            get {
                return ResourceManager.GetString("FireworksSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fills the shape..
        /// </summary>
        internal static string FirstFillColors {
            get {
                return ResourceManager.GetString("FirstFillColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times the effect so that it will fit in the allotted time span..
        /// </summary>
        internal static string FitTime {
            get {
                return ResourceManager.GetString("FitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of flakes..
        /// </summary>
        internal static string FlakeCount {
            get {
                return ResourceManager.GetString("FlakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the type of snowflake..
        /// </summary>
        internal static string FlakeType {
            get {
                return ResourceManager.GetString("FlakeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets flicker frequency in changes per second..
        /// </summary>
        internal static string FlickerFrequency {
            get {
                return ResourceManager.GetString("FlickerFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets percentage of flicker..
        /// </summary>
        internal static string FlickerPercent {
            get {
                return ResourceManager.GetString("FlickerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Flip the direction the Meteor moves..
        /// </summary>
        internal static string FlipDirection {
            get {
                return ResourceManager.GetString("FlipDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text font..
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Font size..
        /// </summary>
        internal static string FontScale {
            get {
                return ResourceManager.GetString("FontScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the frames per second rate..
        /// </summary>
        internal static string FramesPerSecond {
            get {
                return ResourceManager.GetString("FramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the garland type..
        /// </summary>
        internal static string GarlandType {
            get {
                return ResourceManager.GetString("GarlandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from a list of Geometric shapes..
        /// </summary>
        internal static string GeometricShapes {
            get {
                return ResourceManager.GetString("GeometricShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the speed at which a gif animates if the image is a animated gif..
        /// </summary>
        internal static string GifSpeed {
            get {
                return ResourceManager.GetString("GifSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color gradient and brightness curve that are associated together to provide the color(s) for the effect..
        /// </summary>
        internal static string GradientLevelPair {
            get {
                return ResourceManager.GetString("GradientLevelPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the gradient is applied to the effect..
        /// </summary>
        internal static string GradientMode {
            get {
                return ResourceManager.GetString("GradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the stop point for the color in the gradient..
        /// </summary>
        internal static string GradientPosition {
            get {
                return ResourceManager.GetString("GradientPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each element will have all colors generated in parallel..
        /// </summary>
        internal static string GroupColors {
            get {
                return ResourceManager.GetString("GroupColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the grouping together of elements that will be in the same state..
        /// </summary>
        internal static string GroupLevel {
            get {
                return ResourceManager.GetString("GroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow the legs of the spiral..
        /// </summary>
        internal static string Grow {
            get {
                return ResourceManager.GetString("Grow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from a list of Halloween shapes..
        /// </summary>
        internal static string HalloweenShapes {
            get {
                return ResourceManager.GetString("HalloweenShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the height of the fire..
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether there are highlights added..
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the horizontal plane..
        /// </summary>
        internal static string HorizontalOffset {
            get {
                return ResourceManager.GetString("HorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the color of the fire..
        /// </summary>
        internal static string HueShift {
            get {
                return ResourceManager.GetString("HueShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include 45 Point Flakes..
        /// </summary>
        internal static string Include45Pt {
            get {
                return ResourceManager.GetString("Include45Pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the height level of the Initial Snow build-up at the bottom of the element..
        /// </summary>
        internal static string InitialBuildUp {
            get {
                return ResourceManager.GetString("InitialBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Intensity over each iteration..
        /// </summary>
        internal static string IntensityPerIteration {
            get {
                return ResourceManager.GetString("IntensityPerIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies how often the effect should switch in milliseconds..
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the offset into the color list for the alternate state in the effect. One is the default and would shift the colors back and forth by one..
        /// </summary>
        internal static string IntervalSkip {
            get {
                return ResourceManager.GetString("IntervalSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of times the pattern repeats over the timespan..
        /// </summary>
        internal static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Left Border Width..
        /// </summary>
        internal static string LeftBorderWidth {
            get {
                return ResourceManager.GetString("LeftBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a single Phoneme or collection of Marks with Phoneme labels..
        /// </summary>
        internal static string LipSyncMode {
            get {
                return ResourceManager.GetString("LipSyncMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the location..
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lyric verbiage this Phoneme is associated with..
        /// </summary>
        internal static string LyricData {
            get {
                return ResourceManager.GetString("LyricData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping type. Face Mapping or Image Map..
        /// </summary>
        internal static string MappingType {
            get {
                return ResourceManager.GetString("MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mark Collection to align the phoneme movements with. This collection should have the phoneme names for labels..
        /// </summary>
        internal static string MarkCollection {
            get {
                return ResourceManager.GetString("MarkCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mark Labels as text to be displayed..
        /// </summary>
        internal static string MarkLabels {
            get {
                return ResourceManager.GetString("MarkLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezes on the tiem left when triggered..
        /// </summary>
        internal static string MarkTimeFreeze {
            get {
                return ResourceManager.GetString("MarkTimeFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can use the Marks to determine how the effect is rendered..
        /// </summary>
        internal static string MarkType {
            get {
                return ResourceManager.GetString("MarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max angle the Snowflake moves..
        /// </summary>
        internal static string MaxAngle {
            get {
                return ResourceManager.GetString("MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the maximum brightness of a pulse..
        /// </summary>
        internal static string MaxBrightness {
            get {
                return ResourceManager.GetString("MaxBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Direction in Degrees..
        /// </summary>
        internal static string MaxDirection {
            get {
                return ResourceManager.GetString("MaxDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max angle the Meteor moves..
        /// </summary>
        internal static string MaxMeteorAngle {
            get {
                return ResourceManager.GetString("MaxMeteorAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Shape Size..
        /// </summary>
        internal static string MaxShapeSize {
            get {
                return ResourceManager.GetString("MaxShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates Meteors per string..
        /// </summary>
        internal static string MeteorPerString {
            get {
                return ResourceManager.GetString("MeteorPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors are not used when Rainbow is selected..
        /// </summary>
        internal static string MeteorType {
            get {
                return ResourceManager.GetString("MeteorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min angle the Snowflake moves..
        /// </summary>
        internal static string MinAngle {
            get {
                return ResourceManager.GetString("MinAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the minimum brightness of a pulse..
        /// </summary>
        internal static string MinBrightness {
            get {
                return ResourceManager.GetString("MinBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Direction in Degrees..
        /// </summary>
        internal static string MinDirection {
            get {
                return ResourceManager.GetString("MinDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the default brightness of the background in the effect. Sometimes a zero value may be necesary to get certain behaviors in layer mixing..
        /// </summary>
        internal static string MinimumBrightness {
            get {
                return ResourceManager.GetString("MinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min angle the Meteor moves..
        /// </summary>
        internal static string MinMeteorAngle {
            get {
                return ResourceManager.GetString("MinMeteorAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls shape movement..
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls variance of the motion over time..
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the type of movement..
        /// </summary>
        internal static string MovementMode {
            get {
                return ResourceManager.GetString("MovementMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Meteor direction based on X and Y Speed curves..
        /// </summary>
        internal static string MovementSpeed {
            get {
                return ResourceManager.GetString("MovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the effect progresses across time between speed or iterations..
        /// </summary>
        internal static string MovementType {
            get {
                return ResourceManager.GetString("MovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will convert the Offsets to percentage of Buffer size. Once enabled the option will be hidden as this is the updated method..
        /// </summary>
        internal static string OffsetPercentage {
            get {
                return ResourceManager.GetString("OffsetPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage of each on/off cycle that the effect is on..
        /// </summary>
        internal static string OnTime {
            get {
                return ResourceManager.GetString("OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the direction of the strings and controls how the effect is oriented on the element..
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the Outer border start location..
        /// </summary>
        internal static string OuterBorderStarts {
            get {
                return ResourceManager.GetString("OuterBorderStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the outline color..
        /// </summary>
        internal static string OutlineColors {
            get {
                return ResourceManager.GetString("OutlineColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how fast the particles fade..
        /// </summary>
        internal static string ParticleFade {
            get {
                return ResourceManager.GetString("ParticleFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many particles will be created..
        /// </summary>
        internal static string Particles {
            get {
                return ResourceManager.GetString("Particles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled will adjust movement per number where as disabled adjusts movement over effect length..
        /// </summary>
        internal static string PerIteration {
            get {
                return ResourceManager.GetString("PerIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map to use to associate phonemes with images..
        /// </summary>
        internal static string PhonemeMapping {
            get {
                return ResourceManager.GetString("PhonemeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of pixels on each string..
        /// </summary>
        internal static string PixelsPerString {
            get {
                return ResourceManager.GetString("PixelsPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts number of Polygon sides..
        /// </summary>
        internal static string PolygonSides {
            get {
                return ResourceManager.GetString("PolygonSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the centering of the text on the element..
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long each pulse is in milliseconds..
        /// </summary>
        internal static string PulseDuration {
            get {
                return ResourceManager.GetString("PulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many milliseconds the individual pulses overlap..
        /// </summary>
        internal static string PulseOverlap {
            get {
                return ResourceManager.GetString("PulseOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the individual pulse shape..
        /// </summary>
        internal static string PulseShape {
            get {
                return ResourceManager.GetString("PulseShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long each pulse is as a percentage of the spin..
        /// </summary>
        internal static string PulseSpinPercent {
            get {
                return ResourceManager.GetString("PulseSpinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how individual pulses are applied across the effect..
        /// </summary>
        internal static string PulseType {
            get {
                return ResourceManager.GetString("PulseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher the value will result in higher quality but slower render time..
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the direction of the effect to In or out..
        /// </summary>
        internal static string RadialDirection {
            get {
                return ResourceManager.GetString("RadialDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of the radial pattern..
        /// </summary>
        internal static string RadialSpeed {
            get {
                return ResourceManager.GetString("RadialSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The radius of the circle over the time of the effect..
        /// </summary>
        internal static string RadiusCurve {
            get {
                return ResourceManager.GetString("RadiusCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly sets initial shape angle..
        /// </summary>
        internal static string RandomAngle {
            get {
                return ResourceManager.GetString("RandomAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates colors in a random order from teh Color collection..
        /// </summary>
        internal static string RandomColorOrder {
            get {
                return ResourceManager.GetString("RandomColorOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a random or sequential Dissolve..
        /// </summary>
        internal static string RandomDissolve {
            get {
                return ResourceManager.GetString("RandomDissolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the Intensity for each element of the effect..
        /// </summary>
        internal static string RandomIntensity {
            get {
                return ResourceManager.GetString("RandomIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new Meteors at a Random Position.
        /// </summary>
        internal static string RandomPosition {
            get {
                return ResourceManager.GetString("RandomPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates random size balls up to the Radius value...
        /// </summary>
        internal static string RandomRadius {
            get {
                return ResourceManager.GetString("RandomRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly sets initial shape size..
        /// </summary>
        internal static string RandomShapeSize {
            get {
                return ResourceManager.GetString("RandomShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the shape size..
        /// </summary>
        internal static string RandomSize {
            get {
                return ResourceManager.GetString("RandomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Random Speed settings..
        /// </summary>
        internal static string RandomSpeed {
            get {
                return ResourceManager.GetString("RandomSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of times the color pattern repeats within the pattern..
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will repeat the individual words if there are more Marks in the collection then number of total words..
        /// </summary>
        internal static string RepeatText {
            get {
                return ResourceManager.GetString("RepeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverses the Color and Curve depending on direction of Movement curve..
        /// </summary>
        internal static string ReverseColorCurve {
            get {
                return ResourceManager.GetString("ReverseColorCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes direction of effect..
        /// </summary>
        internal static string ReverseDirection {
            get {
                return ResourceManager.GetString("ReverseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many revolutions of the spin will occur..
        /// </summary>
        internal static string RevolutionCount {
            get {
                return ResourceManager.GetString("RevolutionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the frequency in Hz at which the spin occurs..
        /// </summary>
        internal static string RevolutionFrequency {
            get {
                return ResourceManager.GetString("RevolutionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the duration in milliseconds at which the spin occurs..
        /// </summary>
        internal static string RevolutionTime {
            get {
                return ResourceManager.GetString("RevolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Right Border Width..
        /// </summary>
        internal static string RightBorderWidth {
            get {
                return ResourceManager.GetString("RightBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of twist in the spiral..
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rounded corners to the Geometric shapes..
        /// </summary>
        internal static string RoundedCorners {
            get {
                return ResourceManager.GetString("RoundedCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a pixel to the inner corners of the border..
        /// </summary>
        internal static string RoundEdges {
            get {
                return ResourceManager.GetString("RoundEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the percent of the scaling to reduce the size of large images to fit..
        /// </summary>
        internal static string ScalePercent {
            get {
                return ResourceManager.GetString("ScalePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically sets the scaling to match the grid size..
        /// </summary>
        internal static string ScaleToGrid {
            get {
                return ResourceManager.GetString("ScaleToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fills the shape..
        /// </summary>
        internal static string SecondFillColors {
            get {
                return ResourceManager.GetString("SecondFillColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the number of shapes to be created..
        /// </summary>
        internal static string ShapeCount {
            get {
                return ResourceManager.GetString("ShapeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the outline dash length of the shape, used with the line spacing..
        /// </summary>
        internal static string ShapeOutLine {
            get {
                return ResourceManager.GetString("ShapeOutLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the outline space length between dashes of the shape, used with the dash length..
        /// </summary>
        internal static string ShapeOutLineSpace {
            get {
                return ResourceManager.GetString("ShapeOutLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the shape..
        /// </summary>
        internal static string ShapeSize {
            get {
                return ResourceManager.GetString("ShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Height to Width ratio..
        /// </summary>
        internal static string ShapeSizeRatio {
            get {
                return ResourceManager.GetString("ShapeSizeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects Shape catagory..
        /// </summary>
        internal static string ShapeType {
            get {
                return ResourceManager.GetString("ShapeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a 3D effect..
        /// </summary>
        internal static string Show3D {
            get {
                return ResourceManager.GetString("Show3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detemines if the outline of the element is lit..
        /// </summary>
        internal static string ShowOutline {
            get {
                return ResourceManager.GetString("ShowOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink the legs of the spiral..
        /// </summary>
        internal static string Shrink {
            get {
                return ResourceManager.GetString("Shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the radial effect..
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable increase/decrease of shape size based on size variation..
        /// </summary>
        internal static string SizeChange {
            get {
                return ResourceManager.GetString("SizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the shapes size changes..
        /// </summary>
        internal static string SizeMode {
            get {
                return ResourceManager.GetString("SizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the size speed of the shape..
        /// </summary>
        internal static string SizeSpeed {
            get {
                return ResourceManager.GetString("SizeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the size speed around the size speed level by the amount of variation..
        /// </summary>
        internal static string SizeSpeedVariation {
            get {
                return ResourceManager.GetString("SizeSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the shape size around the size level by the amount of variation..
        /// </summary>
        internal static string SizeVariation {
            get {
                return ResourceManager.GetString("SizeVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the skip point for star..
        /// </summary>
        internal static string SkipPoints {
            get {
                return ResourceManager.GetString("SkipPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the Snowflakes to build-up at the bottom of the Element..
        /// </summary>
        internal static string SnowBuildUp {
            get {
                return ResourceManager.GetString("SnowBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the space between garlands..
        /// </summary>
        internal static string Spacing {
            get {
                return ResourceManager.GetString("Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the Speed around the Speed level by the amount of variation..
        /// </summary>
        internal static string SpeedVariation {
            get {
                return ResourceManager.GetString("SpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the individual spins occur..
        /// </summary>
        internal static string SpinSpeedFormat {
            get {
                return ResourceManager.GetString("SpinSpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts inside radius of Star..
        /// </summary>
        internal static string StarInsideSize {
            get {
                return ResourceManager.GetString("StarInsideSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the number of points on the star..
        /// </summary>
        internal static string StarPoints {
            get {
                return ResourceManager.GetString("StarPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting location were the Dissolve or Fill will commence from..
        /// </summary>
        internal static string StartingElement {
            get {
                return ResourceManager.GetString("StartingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines where the Meteors will start from..
        /// </summary>
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the color is a static color..
        /// </summary>
        internal static string StaticColorIndicator {
            get {
                return ResourceManager.GetString("StaticColorIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that the effect should be the same on all elements..
        /// </summary>
        internal static string StaticEffect {
            get {
                return ResourceManager.GetString("StaticEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phoneme mouth affiliation..
        /// </summary>
        internal static string StaticPhoneme {
            get {
                return ResourceManager.GetString("StaticPhoneme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts image dimensions to fit the grid size..
        /// </summary>
        internal static string StretchToGrid {
            get {
                return ResourceManager.GetString("StretchToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of strings the effect will use..
        /// </summary>
        internal static string StringCount {
            get {
                return ResourceManager.GetString("StringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mark Collection to adjust the strobe cycle time based on Mark label value or label duration. When Mark collection label value is selected the label must have a value or a default of 150ms will be used..
        /// </summary>
        internal static string StrobeMarkCollection {
            get {
                return ResourceManager.GetString("StrobeMarkCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Simple or Advanced Strobe control..
        /// </summary>
        internal static string StrobeMode {
            get {
                return ResourceManager.GetString("StrobeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects what source is used to determine change..
        /// </summary>
        internal static string StrobeSource {
            get {
                return ResourceManager.GetString("StrobeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the shape outline..
        /// </summary>
        internal static string StrokeFill {
            get {
                return ResourceManager.GetString("StrokeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the thickness of the shape outline..
        /// </summary>
        internal static string StrokeWidth {
            get {
                return ResourceManager.GetString("StrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of TailLength..
        /// </summary>
        internal static string TailLength {
            get {
                return ResourceManager.GetString("TailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the target elements are treated. Either as individual strings or by their actual location..
        /// </summary>
        internal static string TargetPositioning {
            get {
                return ResourceManager.GetString("TargetPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the brightness of the text in the effect..
        /// </summary>
        internal static string TextBrightness {
            get {
                return ResourceManager.GetString("TextBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the way the text duration is used..
        /// </summary>
        internal static string TextDuration {
            get {
                return ResourceManager.GetString("TextDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will fade the displayed text as per setting..
        /// </summary>
        internal static string TextFade {
            get {
                return ResourceManager.GetString("TextFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to be displayed..
        /// </summary>
        internal static string TextLines {
            get {
                return ResourceManager.GetString("TextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the orientation of the text lines..
        /// </summary>
        internal static string TextMode {
            get {
                return ResourceManager.GetString("TextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use standard Text with no external trigger, Marks to trigger when words are shown or Marks to trigger and use Mark Labels to display..
        /// </summary>
        internal static string TextTrigger {
            get {
                return ResourceManager.GetString("TextTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how thick the spiral leg is..
        /// </summary>
        internal static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the count down in Minutes (over 60sec) or second..
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of time in milliseconds the countdown is shown at each mark..
        /// </summary>
        internal static string TimeVisibleLength {
            get {
                return ResourceManager.GetString("TimeVisibleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects what source is used to determine change..
        /// </summary>
        internal static string TimingSource {
            get {
                return ResourceManager.GetString("TimingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the Top Border Width..
        /// </summary>
        internal static string TopBorderWidth {
            get {
                return ResourceManager.GetString("TopBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how long the averge pulse time is in the twinkle..
        /// </summary>
        internal static string TwinkleAvgPulseTime {
            get {
                return ResourceManager.GetString("TwinkleAvgPulseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much of the effect by percent is covered in twinkles..
        /// </summary>
        internal static string TwinkleCoverage {
            get {
                return ResourceManager.GetString("TwinkleCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether each individual element is twinkled independantly or controled by the depth of the effect..
        /// </summary>
        internal static string TwinkleDepth {
            get {
                return ResourceManager.GetString("TwinkleDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much percent variation in the brightness level of each pulse in the twinkle..
        /// </summary>
        internal static string TwinkleLevelVariation {
            get {
                return ResourceManager.GetString("TwinkleLevelVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much percent variation in the time of each pulse in the twinkle..
        /// </summary>
        internal static string TwinklePulseTimeVariation {
            get {
                return ResourceManager.GetString("TwinklePulseTimeVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the amount of rotation or twist the Pinwheel arm has..
        /// </summary>
        internal static string Twist {
            get {
                return ResourceManager.GetString("Twist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if a underlying base color should be used..
        /// </summary>
        internal static string UseBaseColor {
            get {
                return ResourceManager.GetString("UseBaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the velocity of the particles..
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the orientation of the gradient..
        /// </summary>
        internal static string VerticalBlend {
            get {
                return ResourceManager.GetString("VerticalBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the center positioning of the effect in the vertical plane..
        /// </summary>
        internal static string VerticalOffset {
            get {
                return ResourceManager.GetString("VerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the wave accelerates out from the center over time. .
        /// </summary>
        internal static string WaveAcceleration {
            get {
                return ResourceManager.GetString("WaveAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width over time of the effect..
        /// </summary>
        internal static string WidthCurve {
            get {
                return ResourceManager.GetString("WidthCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the number of passes the wipe makes..
        /// </summary>
        internal static string WipeCount {
            get {
                return ResourceManager.GetString("WipeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the length of the pulse as a percentage of the effect time..
        /// </summary>
        internal static string WipePulsePercent {
            get {
                return ResourceManager.GetString("WipePulsePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how the wipe behaves. Either by a count of passes, or by time related to pulse length..
        /// </summary>
        internal static string WipeType {
            get {
                return ResourceManager.GetString("WipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the Meteors from side to side..
        /// </summary>
        internal static string Wobble {
            get {
                return ResourceManager.GetString("Wobble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the Wobble around the Wobble level by the amount of variation..
        /// </summary>
        internal static string WobbleVariation {
            get {
                return ResourceManager.GetString("WobbleVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can help to adjust the position of the effect. May not work in all cases..
        /// </summary>
        internal static string XOffset {
            get {
                return ResourceManager.GetString("XOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Center Speed.
        /// </summary>
        internal static string XSpeed {
            get {
                return ResourceManager.GetString("XSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the Speed around the center Speed by the amount of variation..
        /// </summary>
        internal static string XSpeedVariation {
            get {
                return ResourceManager.GetString("XSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can help to adjust the position of the effect. May not work in all cases..
        /// </summary>
        internal static string YOffset {
            get {
                return ResourceManager.GetString("YOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Center Speed.
        /// </summary>
        internal static string YSpeed {
            get {
                return ResourceManager.GetString("YSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly adjust the Speed around the center Speed by the amount of variation..
        /// </summary>
        internal static string YSpeedVariation {
            get {
                return ResourceManager.GetString("YSpeedVariation", resourceCulture);
            }
        }
    }
}
