//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VixenModules.EffectEditor.EffectDescriptorAttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EffectDisplayNameDescriptors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectDisplayNameDescriptors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VixenModules.EffectEditor.EffectDescriptorAttributes.EffectDisplayNameDescriptors" +
                            "", typeof(EffectDisplayNameDescriptors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Time.
        /// </summary>
        internal static string AttackTime {
            get {
                return ResourceManager.GetString("AttackTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Pulse Time.
        /// </summary>
        internal static string AveragePulseTime {
            get {
                return ResourceManager.GetString("AveragePulseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Chunks.
        /// </summary>
        internal static string BackgroundChunks {
            get {
                return ResourceManager.GetString("BackgroundChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Skips.
        /// </summary>
        internal static string BackgroundSkips {
            get {
                return ResourceManager.GetString("BackgroundSkips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Color Intensity.
        /// </summary>
        internal static string BaseBrightness {
            get {
                return ResourceManager.GetString("BaseBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Color.
        /// </summary>
        internal static string BaseColor {
            get {
                return ResourceManager.GetString("BaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Type.
        /// </summary>
        internal static string BladeType {
            get {
                return ResourceManager.GetString("BladeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend.
        /// </summary>
        internal static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butterfly Type.
        /// </summary>
        internal static string ButterflyType {
            get {
                return ResourceManager.GetString("ButterflyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Color.
        /// </summary>
        internal static string CenterColor {
            get {
                return ResourceManager.GetString("CenterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Stop.
        /// </summary>
        internal static string CenterStop {
            get {
                return ResourceManager.GetString("CenterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Text.
        /// </summary>
        internal static string CenterText {
            get {
                return ResourceManager.GetString("CenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Percent.
        /// </summary>
        internal static string ChangePercent {
            get {
                return ResourceManager.GetString("ChangePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Gradient.
        /// </summary>
        internal static string ColorGradient {
            get {
                return ResourceManager.GetString("ColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradients.
        /// </summary>
        internal static string ColorGradients {
            get {
                return ResourceManager.GetString("ColorGradients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Handling.
        /// </summary>
        internal static string ColorHandling {
            get {
                return ResourceManager.GetString("ColorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 1.
        /// </summary>
        internal static string ColorOne {
            get {
                return ResourceManager.GetString("ColorOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        internal static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 2.
        /// </summary>
        internal static string ColorTwo {
            get {
                return ResourceManager.GetString("ColorTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Type.
        /// </summary>
        internal static string ColorType {
            get {
                return ResourceManager.GetString("ColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Time.
        /// </summary>
        internal static string DecayTime {
            get {
                return ResourceManager.GetString("DecayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels Deep.
        /// </summary>
        internal static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        internal static string DeviationPercent {
            get {
                return ResourceManager.GetString("DeviationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Brightness.
        /// </summary>
        internal static string EnableMinimumBrightness {
            get {
                return ResourceManager.GetString("EnableMinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosions.
        /// </summary>
        internal static string Explosions {
            get {
                return ResourceManager.GetString("Explosions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Pulse to End.
        /// </summary>
        internal static string ExtendPulseEnd {
            get {
                return ResourceManager.GetString("ExtendPulseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Pulse to Start.
        /// </summary>
        internal static string ExtendPulseStart {
            get {
                return ResourceManager.GetString("ExtendPulseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit To Time.
        /// </summary>
        internal static string FitTime {
            get {
                return ResourceManager.GetString("FitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flake Count.
        /// </summary>
        internal static string FlakeCount {
            get {
                return ResourceManager.GetString("FlakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flake Type.
        /// </summary>
        internal static string FlakeType {
            get {
                return ResourceManager.GetString("FlakeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flicker.
        /// </summary>
        internal static string FlickerPercent {
            get {
                return ResourceManager.GetString("FlickerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garland Type.
        /// </summary>
        internal static string GarlandType {
            get {
                return ResourceManager.GetString("GarlandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Speed.
        /// </summary>
        internal static string GifSpeed {
            get {
                return ResourceManager.GetString("GifSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color &amp; Brightness.
        /// </summary>
        internal static string GradientLevelPair {
            get {
                return ResourceManager.GetString("GradientLevelPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Mode.
        /// </summary>
        internal static string GradientMode {
            get {
                return ResourceManager.GetString("GradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient 1.
        /// </summary>
        internal static string GradientOne {
            get {
                return ResourceManager.GetString("GradientOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient 2.
        /// </summary>
        internal static string GradientTwo {
            get {
                return ResourceManager.GetString("GradientTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Level.
        /// </summary>
        internal static string GroupLevel {
            get {
                return ResourceManager.GetString("GroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pass Filter.
        /// </summary>
        internal static string HighPassFilter {
            get {
                return ResourceManager.GetString("HighPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pass Frequency.
        /// </summary>
        internal static string HighPassFrequency {
            get {
                return ResourceManager.GetString("HighPassFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Shift.
        /// </summary>
        internal static string HueShift {
            get {
                return ResourceManager.GetString("HueShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include 45Pt.
        /// </summary>
        internal static string Include45Pt {
            get {
                return ResourceManager.GetString("Include45Pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Effect Depth.
        /// </summary>
        internal static string IndividualElements {
            get {
                return ResourceManager.GetString("IndividualElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Interval.
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Offset.
        /// </summary>
        internal static string IntervalSkip {
            get {
                return ResourceManager.GetString("IntervalSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        internal static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Pass Filter.
        /// </summary>
        internal static string LowPassFilter {
            get {
                return ResourceManager.GetString("LowPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Pass Frequency.
        /// </summary>
        internal static string LowPassFrequency {
            get {
                return ResourceManager.GetString("LowPassFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Angle.
        /// </summary>
        internal static string MaxAngle {
            get {
                return ResourceManager.GetString("MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string MaxBrightness {
            get {
                return ResourceManager.GetString("MaxBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Direction.
        /// </summary>
        internal static string MaxDirection {
            get {
                return ResourceManager.GetString("MaxDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor Type.
        /// </summary>
        internal static string MeteorType {
            get {
                return ResourceManager.GetString("MeteorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Angle.
        /// </summary>
        internal static string MinAngle {
            get {
                return ResourceManager.GetString("MinAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string MinBrightness {
            get {
                return ResourceManager.GetString("MinBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Direction.
        /// </summary>
        internal static string MinDirection {
            get {
                return ResourceManager.GetString("MinDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Level.
        /// </summary>
        internal static string MinimumBrightness {
            get {
                return ResourceManager.GetString("MinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Level.
        /// </summary>
        internal static string MinimumLevel {
            get {
                return ResourceManager.GetString("MinimumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Type.
        /// </summary>
        internal static string MovementType {
            get {
                return ResourceManager.GetString("MovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Color.
        /// </summary>
        internal static string OuterColor {
            get {
                return ResourceManager.GetString("OuterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Fade.
        /// </summary>
        internal static string ParticleFade {
            get {
                return ResourceManager.GetString("ParticleFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particles.
        /// </summary>
        internal static string Particles {
            get {
                return ResourceManager.GetString("Particles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels Per String.
        /// </summary>
        internal static string PixelsPerString {
            get {
                return ResourceManager.GetString("PixelsPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string PulseDuration {
            get {
                return ResourceManager.GetString("PulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Overlap.
        /// </summary>
        internal static string PulseOverlap {
            get {
                return ResourceManager.GetString("PulseOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Length.
        /// </summary>
        internal static string PulsePercent {
            get {
                return ResourceManager.GetString("PulsePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Intensity.
        /// </summary>
        internal static string PulseShape {
            get {
                return ResourceManager.GetString("PulseShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Type.
        /// </summary>
        internal static string PulseType {
            get {
                return ResourceManager.GetString("PulseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Position.
        /// </summary>
        internal static string RandomPosition {
            get {
                return ResourceManager.GetString("RandomPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Speed.
        /// </summary>
        internal static string RandomSpeed {
            get {
                return ResourceManager.GetString("RandomSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Intensity.
        /// </summary>
        internal static string RandomIntensity {
            get {
                return ResourceManager.GetString("RandomIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution Count.
        /// </summary>
        internal static string RevolutionCount {
            get {
                return ResourceManager.GetString("RevolutionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution.
        /// </summary>
        internal static string RevolutionFrequency {
            get {
                return ResourceManager.GetString("RevolutionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution Time.
        /// </summary>
        internal static string RevolutionTime {
            get {
                return ResourceManager.GetString("RevolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string ScalePercent {
            get {
                return ResourceManager.GetString("ScalePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale To Grid.
        /// </summary>
        internal static string ScaleToGrid {
            get {
                return ResourceManager.GetString("ScaleToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        internal static string Show3D {
            get {
                return ResourceManager.GetString("Show3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string Spacing {
            get {
                return ResourceManager.GetString("Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Format.
        /// </summary>
        internal static string SpeedFormat {
            get {
                return ResourceManager.GetString("SpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Variation.
        /// </summary>
        internal static string SpeedVariation {
            get {
                return ResourceManager.GetString("SpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Effect.
        /// </summary>
        internal static string StaticEffect {
            get {
                return ResourceManager.GetString("StaticEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Count.
        /// </summary>
        internal static string StringCount {
            get {
                return ResourceManager.GetString("StringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail Length.
        /// </summary>
        internal static string TailLength {
            get {
                return ResourceManager.GetString("TailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioning.
        /// </summary>
        internal static string TargetPositioning {
            get {
                return ResourceManager.GetString("TargetPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color Gradients.
        /// </summary>
        internal static string TextColors {
            get {
                return ResourceManager.GetString("TextColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line(s).
        /// </summary>
        internal static string TextLines {
            get {
                return ResourceManager.GetString("TextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Mode.
        /// </summary>
        internal static string TextMode {
            get {
                return ResourceManager.GetString("TextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Base Color.
        /// </summary>
        internal static string UseBaseColor {
            get {
                return ResourceManager.GetString("UseBaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation.
        /// </summary>
        internal static string Variation {
            get {
                return ResourceManager.GetString("Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Blend.
        /// </summary>
        internal static string VerticalBlend {
            get {
                return ResourceManager.GetString("VerticalBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Count.
        /// </summary>
        internal static string WipeCount {
            get {
                return ResourceManager.GetString("WipeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Off.
        /// </summary>
        internal static string WipeOff {
            get {
                return ResourceManager.GetString("WipeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe On.
        /// </summary>
        internal static string WipeOn {
            get {
                return ResourceManager.GetString("WipeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        internal static string XOffset {
            get {
                return ResourceManager.GetString("XOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        internal static string YOffset {
            get {
                return ResourceManager.GetString("YOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
