//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VixenModules.EffectEditor.EffectDescriptorAttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EffectDisplayNameDescriptors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectDisplayNameDescriptors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VixenModules.EffectEditor.EffectDescriptorAttributes.EffectDisplayNameDescriptors" +
                            "", typeof(EffectDisplayNameDescriptors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Mark Gaps.
        /// </summary>
        internal static string AllowMarkGaps {
            get {
                return ResourceManager.GetString("AllowMarkGaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string Amplitude {
            get {
                return ResourceManager.GetString("Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Speed.
        /// </summary>
        internal static string AngleSpeed {
            get {
                return ResourceManager.GetString("AngleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Speed Variation.
        /// </summary>
        internal static string AngleSpeedVariation {
            get {
                return ResourceManager.GetString("AngleSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string Animate {
            get {
                return ResourceManager.GetString("Animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Start Position.
        /// </summary>
        internal static string AnimateXStart {
            get {
                return ResourceManager.GetString("AnimateXStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Start Position.
        /// </summary>
        internal static string AnimateYStart {
            get {
                return ResourceManager.GetString("AnimateYStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Time.
        /// </summary>
        internal static string AttackTime {
            get {
                return ResourceManager.GetString("AttackTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Fit.
        /// </summary>
        internal static string AutoFit {
            get {
                return ResourceManager.GetString("AutoFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Pulse Time.
        /// </summary>
        internal static string AveragePulseTime {
            get {
                return ResourceManager.GetString("AveragePulseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Chunks.
        /// </summary>
        internal static string BackgroundChunks {
            get {
                return ResourceManager.GetString("BackgroundChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackGround Color.
        /// </summary>
        internal static string BackGroundColor {
            get {
                return ResourceManager.GetString("BackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Skips.
        /// </summary>
        internal static string BackgroundSkips {
            get {
                return ResourceManager.GetString("BackgroundSkips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball Count.
        /// </summary>
        internal static string BallCount {
            get {
                return ResourceManager.GetString("BallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string BallEdgeWidth {
            get {
                return ResourceManager.GetString("BallEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string BallFill {
            get {
                return ResourceManager.GetString("BallFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string BallSize {
            get {
                return ResourceManager.GetString("BallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string BallType {
            get {
                return ResourceManager.GetString("BallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Type.
        /// </summary>
        internal static string BarType {
            get {
                return ResourceManager.GetString("BarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Color Intensity.
        /// </summary>
        internal static string BaseBrightness {
            get {
                return ResourceManager.GetString("BaseBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Color.
        /// </summary>
        internal static string BaseColor {
            get {
                return ResourceManager.GetString("BaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Type.
        /// </summary>
        internal static string BladeType {
            get {
                return ResourceManager.GetString("BladeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend.
        /// </summary>
        internal static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string BorderHeight {
            get {
                return ResourceManager.GetString("BorderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Mode.
        /// </summary>
        internal static string BorderMode {
            get {
                return ResourceManager.GetString("BorderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Shapes.
        /// </summary>
        internal static string BorderShapes {
            get {
                return ResourceManager.GetString("BorderShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string BorderSize {
            get {
                return ResourceManager.GetString("BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string BorderThickness {
            get {
                return ResourceManager.GetString("BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Type.
        /// </summary>
        internal static string BorderType {
            get {
                return ResourceManager.GetString("BorderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string BorderWidth {
            get {
                return ResourceManager.GetString("BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Directions.
        /// </summary>
        internal static string BothDirections {
            get {
                return ResourceManager.GetString("BothDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Barrier.
        /// </summary>
        internal static string BottomBarrier {
            get {
                return ResourceManager.GetString("BottomBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Width.
        /// </summary>
        internal static string BottomBorderWidth {
            get {
                return ResourceManager.GetString("BottomBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build-up Speed.
        /// </summary>
        internal static string BuildUpSpeed {
            get {
                return ResourceManager.GetString("BuildUpSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butterfly Type.
        /// </summary>
        internal static string ButterflyType {
            get {
                return ResourceManager.GetString("ButterflyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Color.
        /// </summary>
        internal static string CenterColor {
            get {
                return ResourceManager.GetString("CenterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string CenterSize {
            get {
                return ResourceManager.GetString("CenterSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Stop.
        /// </summary>
        internal static string CenterStop {
            get {
                return ResourceManager.GetString("CenterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Text.
        /// </summary>
        internal static string CenterText {
            get {
                return ResourceManager.GetString("CenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collide Color.
        /// </summary>
        internal static string ChangeCollideColor {
            get {
                return ResourceManager.GetString("ChangeCollideColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Percent.
        /// </summary>
        internal static string ChangePercent {
            get {
                return ResourceManager.GetString("ChangePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chase.
        /// </summary>
        internal static string ChaseTargetNodeSelection {
            get {
                return ResourceManager.GetString("ChaseTargetNodeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Shapes.
        /// </summary>
        internal static string ChristmasShapes {
            get {
                return ResourceManager.GetString("ChristmasShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circles.
        /// </summary>
        internal static string CircleCount {
            get {
                return ResourceManager.GetString("CircleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string CircleEdgeWidth {
            get {
                return ResourceManager.GetString("CircleEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string CircleFill {
            get {
                return ResourceManager.GetString("CircleFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collide.
        /// </summary>
        internal static string Collide {
            get {
                return ResourceManager.GetString("Collide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Array.
        /// </summary>
        internal static string ColorArray {
            get {
                return ResourceManager.GetString("ColorArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Color.
        /// </summary>
        internal static string ColorFill {
            get {
                return ResourceManager.GetString("ColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Gradient.
        /// </summary>
        internal static string ColorGradient {
            get {
                return ResourceManager.GetString("ColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradients.
        /// </summary>
        internal static string ColorGradients {
            get {
                return ResourceManager.GetString("ColorGradients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Handling.
        /// </summary>
        internal static string ColorHandling {
            get {
                return ResourceManager.GetString("ColorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color List.
        /// </summary>
        internal static string ColorList {
            get {
                return ResourceManager.GetString("ColorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 1.
        /// </summary>
        internal static string ColorOne {
            get {
                return ResourceManager.GetString("ColorOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Per Count.
        /// </summary>
        internal static string ColorPerCount {
            get {
                return ResourceManager.GetString("ColorPerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Per Step.
        /// </summary>
        internal static string ColorPerStep {
            get {
                return ResourceManager.GetString("ColorPerStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        internal static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 2.
        /// </summary>
        internal static string ColorTwo {
            get {
                return ResourceManager.GetString("ColorTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Type.
        /// </summary>
        internal static string ColorType {
            get {
                return ResourceManager.GetString("ColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade.
        /// </summary>
        internal static string CountDownFade {
            get {
                return ResourceManager.GetString("CountDownFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Mode.
        /// </summary>
        internal static string CountDownSizeMode {
            get {
                return ResourceManager.GetString("CountDownSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string CountDownTime {
            get {
                return ResourceManager.GetString("CountDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Type.
        /// </summary>
        internal static string CountDownType {
            get {
                return ResourceManager.GetString("CountDownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Per String.
        /// </summary>
        internal static string CountPerString {
            get {
                return ResourceManager.GetString("CountPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Size Ratio.
        /// </summary>
        internal static string CrossSizeRatio {
            get {
                return ResourceManager.GetString("CrossSizeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Color per Character.
        /// </summary>
        internal static string CycleCharacterColor {
            get {
                return ResourceManager.GetString("CycleCharacterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Color.
        /// </summary>
        internal static string CycleColor {
            get {
                return ResourceManager.GetString("CycleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Time.
        /// </summary>
        internal static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Variation.
        /// </summary>
        internal static string CycleVariation {
            get {
                return ResourceManager.GetString("CycleVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Time.
        /// </summary>
        internal static string DecayTime {
            get {
                return ResourceManager.GetString("DecayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels Deep.
        /// </summary>
        internal static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle Threshold.
        /// </summary>
        internal static string DespeckleThreshold {
            get {
                return ResourceManager.GetString("DespeckleThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        internal static string DeviationPercent {
            get {
                return ResourceManager.GetString("DeviationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction Per Word.
        /// </summary>
        internal static string DirectionPerWord {
            get {
                return ResourceManager.GetString("DirectionPerWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions Together.
        /// </summary>
        internal static string DirectionsTogether {
            get {
                return ResourceManager.GetString("DirectionsTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissolve Flip.
        /// </summary>
        internal static string DissolveFlip {
            get {
                return ResourceManager.GetString("DissolveFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Handling.
        /// </summary>
        internal static string EdgeHandling {
            get {
                return ResourceManager.GetString("EdgeHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Intensity.
        /// </summary>
        internal static string EmitterBrightness {
            get {
                return ResourceManager.GetString("EmitterBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Time (ms).
        /// </summary>
        internal static string EmitterOffTime {
            get {
                return ResourceManager.GetString("EmitterOffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Time (ms).
        /// </summary>
        internal static string EmitterOnTime {
            get {
                return ResourceManager.GetString("EmitterOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitters.
        /// </summary>
        internal static string Emitters {
            get {
                return ResourceManager.GetString("Emitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Level.
        /// </summary>
        internal static string EnableGroundLevel {
            get {
                return ResourceManager.GetString("EnableGroundLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Brightness.
        /// </summary>
        internal static string EnableMinimumBrightness {
            get {
                return ResourceManager.GetString("EnableMinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explode Position.
        /// </summary>
        internal static string ExplodePosition {
            get {
                return ResourceManager.GetString("ExplodePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosions.
        /// </summary>
        internal static string Explosions {
            get {
                return ResourceManager.GetString("Explosions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Pulse to End.
        /// </summary>
        internal static string ExtendPulseEnd {
            get {
                return ResourceManager.GetString("ExtendPulseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Pulse to Start.
        /// </summary>
        internal static string ExtendPulseStart {
            get {
                return ResourceManager.GetString("ExtendPulseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Mode.
        /// </summary>
        internal static string EyeMode {
            get {
                return ResourceManager.GetString("EyeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Type.
        /// </summary>
        internal static string Fade {
            get {
                return ResourceManager.GetString("Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Speed.
        /// </summary>
        internal static string FadeSpeed {
            get {
                return ResourceManager.GetString("FadeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Speed.
        /// </summary>
        internal static string FallSpeed {
            get {
                return ResourceManager.GetString("FallSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Spinner.
        /// </summary>
        internal static string FilmSpinner {
            get {
                return ResourceManager.GetString("FilmSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Spinner Gradients.
        /// </summary>
        internal static string FilmSpinnerColors {
            get {
                return ResourceManager.GetString("FilmSpinnerColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Spinner Gradient Mode.
        /// </summary>
        internal static string FilmSpinnerGradientMode {
            get {
                return ResourceManager.GetString("FilmSpinnerGradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireworks Source.
        /// </summary>
        internal static string FireworksSource {
            get {
                return ResourceManager.GetString("FireworksSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Colors 1.
        /// </summary>
        internal static string FirstFillColors {
            get {
                return ResourceManager.GetString("FirstFillColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit To Time.
        /// </summary>
        internal static string FitTime {
            get {
                return ResourceManager.GetString("FitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flake Count.
        /// </summary>
        internal static string FlakeCount {
            get {
                return ResourceManager.GetString("FlakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flake Type.
        /// </summary>
        internal static string FlakeType {
            get {
                return ResourceManager.GetString("FlakeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flicker.
        /// </summary>
        internal static string FlickerPercent {
            get {
                return ResourceManager.GetString("FlickerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Direction.
        /// </summary>
        internal static string FlipDirection {
            get {
                return ResourceManager.GetString("FlipDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Control.
        /// </summary>
        internal static string FlowControl {
            get {
                return ResourceManager.GetString("FlowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Font.
        /// </summary>
        internal static string FontScale {
            get {
                return ResourceManager.GetString("FontScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames Per Color.
        /// </summary>
        internal static string FramesPerColor {
            get {
                return ResourceManager.GetString("FramesPerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garland Type.
        /// </summary>
        internal static string GarlandType {
            get {
                return ResourceManager.GetString("GarlandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Shapes.
        /// </summary>
        internal static string GeometricShapes {
            get {
                return ResourceManager.GetString("GeometricShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Speed.
        /// </summary>
        internal static string GifSpeed {
            get {
                return ResourceManager.GetString("GifSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color &amp; Brightness.
        /// </summary>
        internal static string GradientLevelPair {
            get {
                return ResourceManager.GetString("GradientLevelPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Mode.
        /// </summary>
        internal static string GradientMode {
            get {
                return ResourceManager.GetString("GradientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient 1.
        /// </summary>
        internal static string GradientOne {
            get {
                return ResourceManager.GetString("GradientOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient 2.
        /// </summary>
        internal static string GradientTwo {
            get {
                return ResourceManager.GetString("GradientTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Colors.
        /// </summary>
        internal static string GroupColors {
            get {
                return ResourceManager.GetString("GroupColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Level.
        /// </summary>
        internal static string GroupLevel {
            get {
                return ResourceManager.GetString("GroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween Shapes.
        /// </summary>
        internal static string HalloweenShapes {
            get {
                return ResourceManager.GetString("HalloweenShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Flake Count.
        /// </summary>
        internal static string HFlakeCount {
            get {
                return ResourceManager.GetString("HFlakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pass Filter.
        /// </summary>
        internal static string HighPassFilter {
            get {
                return ResourceManager.GetString("HighPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pass Frequency.
        /// </summary>
        internal static string HighPassFrequency {
            get {
                return ResourceManager.GetString("HighPassFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Offset.
        /// </summary>
        internal static string HorizontalOffset {
            get {
                return ResourceManager.GetString("HorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Shift.
        /// </summary>
        internal static string HueShift {
            get {
                return ResourceManager.GetString("HueShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include 45Pt.
        /// </summary>
        internal static string Include45Pt {
            get {
                return ResourceManager.GetString("Include45Pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Depth.
        /// </summary>
        internal static string IndividualElements {
            get {
                return ResourceManager.GetString("IndividualElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Build-up.
        /// </summary>
        internal static string InitialBuildUp {
            get {
                return ResourceManager.GetString("InitialBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity Per Iteration.
        /// </summary>
        internal static string IntensityPerIteration {
            get {
                return ResourceManager.GetString("IntensityPerIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Interval.
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Offset.
        /// </summary>
        internal static string IntervalSkip {
            get {
                return ResourceManager.GetString("IntervalSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        internal static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Barrier.
        /// </summary>
        internal static string LeftBarrier {
            get {
                return ResourceManager.GetString("LeftBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Width.
        /// </summary>
        internal static string LeftBorderWidth {
            get {
                return ResourceManager.GetString("LeftBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoneme / Marks.
        /// </summary>
        internal static string LipSyncMode {
            get {
                return ResourceManager.GetString("LipSyncMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Pass Filter.
        /// </summary>
        internal static string LowPassFilter {
            get {
                return ResourceManager.GetString("LowPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Pass Frequency.
        /// </summary>
        internal static string LowPassFrequency {
            get {
                return ResourceManager.GetString("LowPassFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyric.
        /// </summary>
        internal static string LyricData {
            get {
                return ResourceManager.GetString("LyricData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Type.
        /// </summary>
        internal static string MappingType {
            get {
                return ResourceManager.GetString("MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Collection.
        /// </summary>
        internal static string MarkCollection {
            get {
                return ResourceManager.GetString("MarkCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mark Labels.
        /// </summary>
        internal static string MarkLabels {
            get {
                return ResourceManager.GetString("MarkLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Type.
        /// </summary>
        internal static string MarkType {
            get {
                return ResourceManager.GetString("MarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Angle.
        /// </summary>
        internal static string MaxAngle {
            get {
                return ResourceManager.GetString("MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string MaxBrightness {
            get {
                return ResourceManager.GetString("MaxBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Direction.
        /// </summary>
        internal static string MaxDirection {
            get {
                return ResourceManager.GetString("MaxDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size.
        /// </summary>
        internal static string MaxShapeSize {
            get {
                return ResourceManager.GetString("MaxShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor Per String.
        /// </summary>
        internal static string MeteorPerString {
            get {
                return ResourceManager.GetString("MeteorPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor Type.
        /// </summary>
        internal static string MeteorType {
            get {
                return ResourceManager.GetString("MeteorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Angle.
        /// </summary>
        internal static string MinAngle {
            get {
                return ResourceManager.GetString("MinAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string MinBrightness {
            get {
                return ResourceManager.GetString("MinBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Direction.
        /// </summary>
        internal static string MinDirection {
            get {
                return ResourceManager.GetString("MinDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Level.
        /// </summary>
        internal static string MinimumBrightness {
            get {
                return ResourceManager.GetString("MinimumBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Level.
        /// </summary>
        internal static string MinimumLevel {
            get {
                return ResourceManager.GetString("MinimumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        internal static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Colors.
        /// </summary>
        internal static string MixColors {
            get {
                return ResourceManager.GetString("MixColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Speed.
        /// </summary>
        internal static string MovementSpeed {
            get {
                return ResourceManager.GetString("MovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        internal static string MovementType {
            get {
                return ResourceManager.GetString("MovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle Angle.
        /// </summary>
        internal static string NozzleAngle {
            get {
                return ResourceManager.GetString("NozzleAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle Movement.
        /// </summary>
        internal static string NozzleMovement {
            get {
                return ResourceManager.GetString("NozzleMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle Size.
        /// </summary>
        internal static string NozzleSize {
            get {
                return ResourceManager.GetString("NozzleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle Speed.
        /// </summary>
        internal static string NozzleSpeed {
            get {
                return ResourceManager.GetString("NozzleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Percentage.
        /// </summary>
        internal static string OffsetPercentage {
            get {
                return ResourceManager.GetString("OffsetPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Time.
        /// </summary>
        internal static string OnTime {
            get {
                return ResourceManager.GetString("OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscillate End Angle.
        /// </summary>
        internal static string OscillateEndAngle {
            get {
                return ResourceManager.GetString("OscillateEndAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscillate Start Angle.
        /// </summary>
        internal static string OscillateStartAngle {
            get {
                return ResourceManager.GetString("OscillateStartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Border Starts.
        /// </summary>
        internal static string OuterBorderStarts {
            get {
                return ResourceManager.GetString("OuterBorderStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Color.
        /// </summary>
        internal static string OuterColor {
            get {
                return ResourceManager.GetString("OuterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Colors.
        /// </summary>
        internal static string OutlineColors {
            get {
                return ResourceManager.GetString("OutlineColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Color.
        /// </summary>
        internal static string ParticleColor {
            get {
                return ResourceManager.GetString("ParticleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Fade.
        /// </summary>
        internal static string ParticleFade {
            get {
                return ResourceManager.GetString("ParticleFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Lifetime.
        /// </summary>
        internal static string ParticleLifetime {
            get {
                return ResourceManager.GetString("ParticleLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particles.
        /// </summary>
        internal static string Particles {
            get {
                return ResourceManager.GetString("Particles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Size.
        /// </summary>
        internal static string ParticleSize {
            get {
                return ResourceManager.GetString("ParticleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Type.
        /// </summary>
        internal static string ParticleType {
            get {
                return ResourceManager.GetString("ParticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Velocity.
        /// </summary>
        internal static string ParticleVelocity {
            get {
                return ResourceManager.GetString("ParticleVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement per number.
        /// </summary>
        internal static string PerIteration {
            get {
                return ResourceManager.GetString("PerIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Shift.
        /// </summary>
        internal static string PhaseShift {
            get {
                return ResourceManager.GetString("PhaseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Map.
        /// </summary>
        internal static string PhonemeMapping {
            get {
                return ResourceManager.GetString("PhonemeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels Per String.
        /// </summary>
        internal static string PixelsPerString {
            get {
                return ResourceManager.GetString("PixelsPerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon Sides.
        /// </summary>
        internal static string PolygonSides {
            get {
                return ResourceManager.GetString("PolygonSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Wave.
        /// </summary>
        internal static string PrimeWave {
            get {
                return ResourceManager.GetString("PrimeWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string PulseDuration {
            get {
                return ResourceManager.GetString("PulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Overlap.
        /// </summary>
        internal static string PulseOverlap {
            get {
                return ResourceManager.GetString("PulseOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Length.
        /// </summary>
        internal static string PulsePercent {
            get {
                return ResourceManager.GetString("PulsePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Intensity.
        /// </summary>
        internal static string PulseShape {
            get {
                return ResourceManager.GetString("PulseShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Type.
        /// </summary>
        internal static string PulseType {
            get {
                return ResourceManager.GetString("PulseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string RadialDirection {
            get {
                return ResourceManager.GetString("RadialDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string RadialSpeed {
            get {
                return ResourceManager.GetString("RadialSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Angle.
        /// </summary>
        internal static string RandomAngle {
            get {
                return ResourceManager.GetString("RandomAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Color Order.
        /// </summary>
        internal static string RandomColorOrder {
            get {
                return ResourceManager.GetString("RandomColorOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Dissolve.
        /// </summary>
        internal static string RandomDissolve {
            get {
                return ResourceManager.GetString("RandomDissolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Intensity.
        /// </summary>
        internal static string RandomIntensity {
            get {
                return ResourceManager.GetString("RandomIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Time.
        /// </summary>
        internal static string RandomMaxCurve {
            get {
                return ResourceManager.GetString("RandomMaxCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Movement.
        /// </summary>
        internal static string RandomMovement {
            get {
                return ResourceManager.GetString("RandomMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Position.
        /// </summary>
        internal static string RandomPosition {
            get {
                return ResourceManager.GetString("RandomPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Radius.
        /// </summary>
        internal static string RandomRadius {
            get {
                return ResourceManager.GetString("RandomRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Size.
        /// </summary>
        internal static string RandomSize {
            get {
                return ResourceManager.GetString("RandomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Speed.
        /// </summary>
        internal static string RandomSpeed {
            get {
                return ResourceManager.GetString("RandomSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Start.
        /// </summary>
        internal static string RandomStartingPosition {
            get {
                return ResourceManager.GetString("RandomStartingPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Scale Factor.
        /// </summary>
        internal static string RenderScaleFactor {
            get {
                return ResourceManager.GetString("RenderScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Text.
        /// </summary>
        internal static string RepeatText {
            get {
                return ResourceManager.GetString("RepeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string ReverseColorCurve {
            get {
                return ResourceManager.GetString("ReverseColorCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Direction.
        /// </summary>
        internal static string ReverseDirection {
            get {
                return ResourceManager.GetString("ReverseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution Count.
        /// </summary>
        internal static string RevolutionCount {
            get {
                return ResourceManager.GetString("RevolutionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution.
        /// </summary>
        internal static string RevolutionFrequency {
            get {
                return ResourceManager.GetString("RevolutionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution Time.
        /// </summary>
        internal static string RevolutionTime {
            get {
                return ResourceManager.GetString("RevolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Barrier.
        /// </summary>
        internal static string RightBarrier {
            get {
                return ResourceManager.GetString("RightBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Width.
        /// </summary>
        internal static string RightBorderWidth {
            get {
                return ResourceManager.GetString("RightBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounded Corners.
        /// </summary>
        internal static string RoundedCorners {
            get {
                return ResourceManager.GetString("RoundedCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Edges.
        /// </summary>
        internal static string RoundEdges {
            get {
                return ResourceManager.GetString("RoundEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string ScalePercent {
            get {
                return ResourceManager.GetString("ScalePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale To Grid.
        /// </summary>
        internal static string ScaleToGrid {
            get {
                return ResourceManager.GetString("ScaleToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Colors 2.
        /// </summary>
        internal static string SecondFillColors {
            get {
                return ResourceManager.GetString("SecondFillColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ShapeCount {
            get {
                return ResourceManager.GetString("ShapeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutLine Dash Length.
        /// </summary>
        internal static string ShapeOutLine {
            get {
                return ResourceManager.GetString("ShapeOutLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutLine Space Length.
        /// </summary>
        internal static string ShapeOutLineSpace {
            get {
                return ResourceManager.GetString("ShapeOutLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ShapeSize {
            get {
                return ResourceManager.GetString("ShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Ratio.
        /// </summary>
        internal static string ShapeSizeRatio {
            get {
                return ResourceManager.GetString("ShapeSizeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ShapeType {
            get {
                return ResourceManager.GetString("ShapeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        internal static string Show3D {
            get {
                return ResourceManager.GetString("Show3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Outline.
        /// </summary>
        internal static string ShowOutline {
            get {
                return ResourceManager.GetString("ShowOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Change.
        /// </summary>
        internal static string SizeChange {
            get {
                return ResourceManager.GetString("SizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Mode.
        /// </summary>
        internal static string SizeMode {
            get {
                return ResourceManager.GetString("SizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Speed.
        /// </summary>
        internal static string SizeSpeed {
            get {
                return ResourceManager.GetString("SizeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Speed Variation.
        /// </summary>
        internal static string SizeSpeedVariation {
            get {
                return ResourceManager.GetString("SizeSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Variation.
        /// </summary>
        internal static string SizeVariation {
            get {
                return ResourceManager.GetString("SizeVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Skip Points.
        /// </summary>
        internal static string SkipPoints {
            get {
                return ResourceManager.GetString("SkipPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snake Length.
        /// </summary>
        internal static string SnakeLength {
            get {
                return ResourceManager.GetString("SnakeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow Build-up.
        /// </summary>
        internal static string SnowBuildUp {
            get {
                return ResourceManager.GetString("SnowBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string Spacing {
            get {
                return ResourceManager.GetString("Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Format.
        /// </summary>
        internal static string SpeedFormat {
            get {
                return ResourceManager.GetString("SpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Variation.
        /// </summary>
        internal static string SpeedVariation {
            get {
                return ResourceManager.GetString("SpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        internal static string SpinTargetNodeSelection {
            get {
                return ResourceManager.GetString("SpinTargetNodeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Center Radius.
        /// </summary>
        internal static string StarInsideSize {
            get {
                return ResourceManager.GetString("StarInsideSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Points.
        /// </summary>
        internal static string StarPoints {
            get {
                return ResourceManager.GetString("StarPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Element.
        /// </summary>
        internal static string StartingElement {
            get {
                return ResourceManager.GetString("StartingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Position.
        /// </summary>
        internal static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Effect.
        /// </summary>
        internal static string StaticEffect {
            get {
                return ResourceManager.GetString("StaticEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoneme.
        /// </summary>
        internal static string StaticPhoneme {
            get {
                return ResourceManager.GetString("StaticPhoneme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch To Grid.
        /// </summary>
        internal static string StretchToGrid {
            get {
                return ResourceManager.GetString("StretchToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Count.
        /// </summary>
        internal static string StringCount {
            get {
                return ResourceManager.GetString("StringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe Mode.
        /// </summary>
        internal static string StrobeMode {
            get {
                return ResourceManager.GetString("StrobeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe Source.
        /// </summary>
        internal static string StrobeSource {
            get {
                return ResourceManager.GetString("StrobeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Fill.
        /// </summary>
        internal static string StrokeFill {
            get {
                return ResourceManager.GetString("StrokeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Thickness.
        /// </summary>
        internal static string StrokeWidth {
            get {
                return ResourceManager.GetString("StrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail Length.
        /// </summary>
        internal static string TailLength {
            get {
                return ResourceManager.GetString("TailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioning.
        /// </summary>
        internal static string TargetPositioning {
            get {
                return ResourceManager.GetString("TargetPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color Gradients.
        /// </summary>
        internal static string TextColors {
            get {
                return ResourceManager.GetString("TextColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Duration.
        /// </summary>
        internal static string TextDuration {
            get {
                return ResourceManager.GetString("TextDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Fade.
        /// </summary>
        internal static string TextFade {
            get {
                return ResourceManager.GetString("TextFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line(s).
        /// </summary>
        internal static string TextLines {
            get {
                return ResourceManager.GetString("TextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Mode.
        /// </summary>
        internal static string TextMode {
            get {
                return ResourceManager.GetString("TextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Trigger.
        /// </summary>
        internal static string TextTrigger {
            get {
                return ResourceManager.GetString("TextTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Format.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Time Length (ms).
        /// </summary>
        internal static string TimeVisibleLength {
            get {
                return ResourceManager.GetString("TimeVisibleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing Source.
        /// </summary>
        internal static string TimingSource {
            get {
                return ResourceManager.GetString("TimingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Barrier.
        /// </summary>
        internal static string TopBarrier {
            get {
                return ResourceManager.GetString("TopBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Width.
        /// </summary>
        internal static string TopBorderWidth {
            get {
                return ResourceManager.GetString("TopBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Base Color.
        /// </summary>
        internal static string UseBaseColor {
            get {
                return ResourceManager.GetString("UseBaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Color List.
        /// </summary>
        internal static string UseColorList {
            get {
                return ResourceManager.GetString("UseColorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Marks.
        /// </summary>
        internal static string UseMarks {
            get {
                return ResourceManager.GetString("UseMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation.
        /// </summary>
        internal static string Variation {
            get {
                return ResourceManager.GetString("Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity X.
        /// </summary>
        internal static string VelocityX {
            get {
                return ResourceManager.GetString("VelocityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Y.
        /// </summary>
        internal static string VelocityY {
            get {
                return ResourceManager.GetString("VelocityY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Blend.
        /// </summary>
        internal static string VerticalBlend {
            get {
                return ResourceManager.GetString("VerticalBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Offset.
        /// </summary>
        internal static string VerticalOffset {
            get {
                return ResourceManager.GetString("VerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Flake Count.
        /// </summary>
        internal static string VFlakeCount {
            get {
                return ResourceManager.GetString("VFlakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Up Frames.
        /// </summary>
        internal static string WarmUpFrames {
            get {
                return ResourceManager.GetString("WarmUpFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Type.
        /// </summary>
        internal static string WaveMovementType {
            get {
                return ResourceManager.GetString("WaveMovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Type.
        /// </summary>
        internal static string WaveType {
            get {
                return ResourceManager.GetString("WaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Count.
        /// </summary>
        internal static string WipeCount {
            get {
                return ResourceManager.GetString("WipeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Off.
        /// </summary>
        internal static string WipeOff {
            get {
                return ResourceManager.GetString("WipeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe On.
        /// </summary>
        internal static string WipeOn {
            get {
                return ResourceManager.GetString("WipeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wobble.
        /// </summary>
        internal static string Wobble {
            get {
                return ResourceManager.GetString("Wobble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wobble Variation.
        /// </summary>
        internal static string WobbleVariation {
            get {
                return ResourceManager.GetString("WobbleVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        internal static string XOffset {
            get {
                return ResourceManager.GetString("XOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Position.
        /// </summary>
        internal static string XPosition {
            get {
                return ResourceManager.GetString("XPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Center Speed.
        /// </summary>
        internal static string XSpeed {
            get {
                return ResourceManager.GetString("XSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Speed Variation.
        /// </summary>
        internal static string XSpeedVariation {
            get {
                return ResourceManager.GetString("XSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        internal static string YOffset {
            get {
                return ResourceManager.GetString("YOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Position.
        /// </summary>
        internal static string YPosition {
            get {
                return ResourceManager.GetString("YPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Center Speed.
        /// </summary>
        internal static string YSpeed {
            get {
                return ResourceManager.GetString("YSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Speed Variation.
        /// </summary>
        internal static string YSpeedVariation {
            get {
                return ResourceManager.GetString("YSpeedVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string ZigZagAmplitude {
            get {
                return ResourceManager.GetString("ZigZagAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string ZigZagPeriod {
            get {
                return ResourceManager.GetString("ZigZagPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string ZigZagSpacing {
            get {
                return ResourceManager.GetString("ZigZagSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string ZigZagThickness {
            get {
                return ResourceManager.GetString("ZigZagThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
