name: Auto approve PRs for merge approved by Vixen Developer Team members

on:
  workflow_run:
      workflows: ["Review Submitted"]
      types:
        - completed

jobs:
  # Auto approve PR with Vixen Developer Team member approval
  setup-auto-approve:
    runs-on: ubuntu-latest
    outputs:
      reviewed: ${{ steps.setup.outputs.reviewed }}
      actor: ${{ steps.setup.outputs.actor }}
      pr_number: ${{ steps.setup.outputs.pr_number }}
    
    steps:
      - name: Download pr review artifacts
        uses: actions/download-artifact@v4
        with:
          name: pr_review_info
          path: ./downloaded-data

      - name: setup
        run: |
          # Read file content (e.g., "review_state|pr_number|review_actor")
          PR_INFO=$(cat ./downloaded-data/pr_review_info)
          
          # Split by | and assign to temporary bash variables
          IFS='|' read -r REVIEW_STATE PR_NUMBER ACTOR <<< "PR_INFO"

          if [ "$REVIEW_STATE" == "approved" ]; then
            echo "reviewed=true" >> $GITHUB_OUTPUT
          else
            echo "reviewed=false" >> $GITHUB_OUTPUT
          fi
         
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT

  auto-approve:
    runs-on: ubuntu-latest
    needs: setup-auto-approve
    if: ${{ needs.setup-auto-approve.outputs.reviewed == 'true' }}
    permissions:
      pull-requests: write

    steps:
      - name: Check user for Vixen Developer Team affiliation
        id: teamAffiliation
        uses: tspascoal/get-user-teams-membership@v3
        with:
          username: ${{ needs.setup-auto-approve.outputs.actor }}
          team: Vixen Developers
          GITHUB_TOKEN: ${{ secrets.READ_ORG_MEMBERS }}

      - name: Show Vixen Developer Team affiliation output
        run: |
          echo "The output was ${{ steps.teamAffiliation.outputs.isTeamMember }}"

      - name: Check user for Vixen Maintainer Team affiliation
        id: maintainerAffiliation
        uses: tspascoal/get-user-teams-membership@v3
        with:
          username: ${{ needs.setup-auto-approve.outputs.actor }}
          team: Vixen Maintainer
          GITHUB_TOKEN: ${{ secrets.READ_ORG_MEMBERS }}

      - name: Show Vixen Maintainer Team affiliation output
        run: echo "The output was ${{ steps.maintainerAffiliation.outputs.isTeamMember }}"

      - name: Auto approve if team member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'true' && steps.maintainerAffiliation.outputs.isTeamMember == 'false' }}
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ needs.setup-auto-approve.outputs.pr_number }}
          review-message: "Auto approved with Vixen Developer Team member approval"
